Class ClassicTeleportFog : TeleportFog{}
Class AllyPathfinder : SGMKAllyActor {
	class<Actor> allyClass;
	property allyClass : allyClass;
	Default{
		Radius 32;
		Height 56;
		Speed 20;
		Health 4000;
		PainChance 255;
		MaxTargetRange 150;
		Monster;
		damagefactor "SpawnMarine", 8000.0;
		MaxDropOffHeight 1200;
		MaxStepHeight 1200;
		-COUNTKILL
		+NOTARGET
		+THRUACTORS
		+MISSILEMORE
		+MISSILEEVENMORE
		+FASTER
		+DONTSPLASH
		-SHOOTABLE
		-FRIENDLY
		+NOCLIP
		+LOOKALLAROUND
		+NOINFIGHTING
		//+AVOIDHAZARDS
	}
	override void PostBeginPlay(){
		if (allyClass){
			A_SetSize(GetDefaultbyType(allyClass).height,GetDefaultbyType(allyClass).radius);
		}
		//if(!(master is "PlayerPawn")){master = players[0].mo;}//GetClosestPlayer();}
		target = players[0].mo;
		Super.PostBeginPlay();
	}
	override void Tick()
	{
		target = players[0].mo;//GetClosestPlayer();
		if ( !CheckIfCloser(target, radius, false) ){ //&& !(CountInv("PathfinderActivate")>0)
			if(bFLOORHUGGER){A_Warp(AAPTR_TARGET,0,0,0,0,WARPF_TOFLOOR);}
			else{A_Warp(AAPTR_TARGET);}
		}
		if ( CheckIfCloser(target, radius, false) ){ //(target.Distance3D(self) < radius) 
			State Missile = FindState('Missile');
			if (Missile) SetState(FindState("Missile"));
		}
		super.Tick();
	}
	bool CheckBlockDec (int flags = 0, int ptr = AAPTR_DEFAULT, double xofs = 0, double yofs = 0, double zofs = 0, double angle = 0){
		return CheckBlock(flags, ptr, xofs, yofs, zofs, angle);
	}
	
	void A_AllySpawn(){
		if (allyClass){
			A_SpawnItemEx(allyClass,-30,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET);
			A_SpawnItemEx("TeleportFog",-30,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET);
		}
	}
	void A_AllyWarp(){
		if(master && master is "PBMarine" && master.master){
			master.A_Warp(AAPTR_MASTER,-30,0,0,0);
			target.A_SpawnItemEx("ClassicTeleportFog",-30,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET);
		}
	}
	States{
	Spawn:
	Pain:
	See:
	Pathfind:
		TNT1 A 0 NODELAY {A_ChangeFlag("FRIENDLY", 0);A_ChangeFlag("NOCLIP", 1);}//A_TakeInventory("PathfinderActivate", 1);}
		TNT1 A 0 A_FindPlayerTarget;
		TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
		TNT1 AAAAA 1 {A_FaceTarget();A_Chase();}//{A_Chase;A_Warp(AAPTR_TARGET);}
		TNT1 A 0 A_Jump(256,"See");
		Loop;
	Missile:
		TNT1 A 0 ;
		TNT1 A 0 NODELAY A_ChangeFlag("NOCLIP", 0);
		TNT1 A 0 A_Recoil(-4);
		TNT1 A 1 ;//A_GiveInventory("PathfinderActivate", 1);
		TNT1 A 0 A_JumpIf(momx == 0, "CheckAgain");
		TNT1 A 0 A_Jump(256,"SpawnAllyStart");
		goto SpawnAllyStart;
	SpawnAllyStart:
		TNT1 A 0 ;
		TNT1 A 0 NODELAY A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(256,"SpawnAlly");
	SpawnAlly:
	Death:
	XDeath:
		TNT1 A 0 ;
		TNT1 A 0 A_AllyWarp();/*{
			if(pb_marineswarp){A_AllyWarp();}
			else{A_AllySpawn();}
		}*/
		Stop;
	CheckAgain:
		TNT1 A 0 ;//A_DebugLog("Checking Again");
		TNT1 A 0 NODELAY A_JumpIF(momy == 0, "See");
		TNT1 A 0 A_Jump(256,"SpawnAllyStart");
		Goto SpawnAllyStart;
	}
}

Class RemoveMarineActivateZScript : Actor {
	string AllyCountedInventory;
	property AllyCountedInventory : AllyCountedInventory;
	Default{
	Radius 32;
	Height 56;
	Health 4000;
	PainChance 255;
	Monster;
	damagefactor "SpawnMarine", 8000.0;
	MaxDropOffHeight 1200;
	MaxStepHeight 1200;
	-COUNTKILL
	+NOTARGET
	+THRUACTORS
	+MISSILEMORE
	+MISSILEEVENMORE
	+FASTER
	+DONTSPLASH
	-SHOOTABLE
	-FRIENDLY
	+NOCLIP
	+LOOKALLAROUND
	+NOINFIGHTING
	Scale 1.0;
	Speed 1;
	MaxTargetRange 90000;
	}
	States
	{
	Spawn:
	Pain:
	See:
		TNT1 A 0 A_ChangeFlag("FRIENDLY", 0);
		TNT1 A 0 Thing_ChangeTID(0,98);
		TNT1 AAAAAAAAAAAAAAAAA 1 A_Chase;
		TNT1 A 0 A_Recoil(-5);
		TNT1 A 1 A_FaceTarget;
		Loop;
	Missile:
		TNT1 A 1 A_TakeFromTarget(AllyCountedInventory, 1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 1;
		Stop;
	}
}