extend class PBMarine{
	States{
		CheckRetreat:
			#### # 0 A_JumpIfCloser(500, "Retreat");
			#### # 0 A_Jump(256,"Pain.Avoid");
		Pain.Avoid:
			#### # 0 A_JumpStrafe;
			#### # 0 A_Jump(256,"Retreat");
		FIRECHECK:
			---- A 1 A_JumpIfTargetInLOS("Missile2", 0, JLOSF_DEADNOJUMP);
			---- A 0 A_Jump(256,"See");
		Waits3:
			---- A 0 D_StartReloadIfNotFull;
			---- A 0 A_JumpIf(!pb_marinesgiveammo, 3);
			---- A 0 A_JumpIfInTargetInventory("PB_LowCalMag", 20, 2);
			---- A 0 A_Jump(256,"GiveAmmo");
			---- A 0 A_JumpIf(!pb_marinesgivehealth, 2);
			---- A 0 A_JumpIfHealthLower(40, "GiveHealth",AAPTR_MASTER);
			---- A 0 A_Jump(256, "Waits4");
		GiveAmmo:
			PLAY A 10 A_FaceTarget;
			PLAY B 30 A_StartVoiceLine("MRNGI1");
			goto HandOverAmmo;
		HandOverAmmo:
			#### # 0 A_GiveToTarget("PB_LowCalMag", 20);
			#### # 0 A_Jump(256,"Waits");
		GiveHealth:
			PLAY A 10 A_FaceTarget;
			PLAY B 30 A_StartVoiceLine("MRNGI2");
			goto HandOverStimpack;
		HandOverStimpack:
			#### # 0 A_GiveToTarget("PB_Stimpack");
			#### # 0 A_Jump(256,"Waits");
		Salute:
			#### # 0 A_Jump(256, "Salutes1", "Salutes2");
		Salutes1:
			MWAV B 6 A_PlaySound ("DSSALUTE");
			MWAV CDEFEFDCB 6;
			#### # 0 A_Jump(256,"FollowPlayer");
		Salutes2:
			MWAV G 8 A_PlaySound ("DSSALUTE");
			MWAV HGHG 8;
			#### # 0 A_Jump(256,"FollowPlayer");
		MarineSequence:
			---- A 1;
			#### # 0 A_ChangeFlag("NODROPOFF", 1);
			#### # 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");
			#### # 0 A_JumpIfTargetIsPlayer("CheckRangeToWait");
			#### # 0 {A_ChangeFlag("SHOOTABLE", 1);A_ChangeFlag("SOLID", 1);}
			#### # 0 A_JumpIfCloser(60, "AttackMelee");
			#### # 0 A_JumpIfCloser(300, "Retreat");
			#### # 0 A_Jump(256,"See");
		Execution_Generic:
		AttackExecute:
			PLA1 H 6 ;
			PLA1 E 2 A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			PLA1 A 8 {
				A_SpawnProjectile("ShakeYourAss",40,0,0,0,0,0);
				A_StartSound("execution/impact", CHAN_AUTO);
			}
			PLA1 BBCHH 2;
			PLA1 F 2 {
				A_StartSound("weapons/ultrwhoosh", CHAN_AUTO);
			}
			PLA1 D 8 {
				A_SpawnProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_StartSound("gore/heavyimpact", CHAN_AUTO);
			}
			PLA1 AB 3;
			#### # 0 A_Jump(256,"See");
		CheckRetreat:
			#### # 1 A_JumpIfCloser(500, "Retreat");
			#### # 0 A_Jump(256,"Pain.Avoid");
		Pain.Avoid:	
			#### # 1 A_JumpStrafe;
			#### # 0 A_Jump(256,"Retreat");
		StrafeLeft:
			//"####"
			PLAY A 3 A_FaceTarget;
			PLAY B 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			PLAY C 3 A_FaceTarget;
			PLAY D 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			TNT1 D 0 A_JumpIfReloading("See");
			#### # 0 A_Jump(256,"Missile2");
		StrafeRight:
			PLAY A 3 A_FaceTarget;
			PLAY B 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			PLAY C 3 A_FaceTarget;
			PLAY D 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			TNT1 D 0 A_JumpIfReloading("See");
			#### # 0 A_Jump(256,"Missile2");
		Pain.Kick:
			PLAY A 2 A_FaceTarget;
			#### # 0 A_Recoil(5);
			#### # 0 A_Jump(256,"FollowPlayer");
		Pain:
			PLAY G 3 A_Pain;
			PLAY G 3 A_ChangeFlag("NODROPOFF", 0);
			#### # 0 A_Jump(256,"FollowPlayer");
		FIRECHECK:
			---- A 1 A_JumpIfTargetInLOS("Missile2", 0, JLOSF_DEADNOJUMP);
			---- A 0 A_Jump(256,"See");
		GiveAmmo:
			PLAY A 10 A_FaceTarget;
			PLAY B 30 A_StartVoiceLine("MRNGI1");
			goto HandOverAmmo;
		HandOverAmmo:
			#### # 0 A_GiveToTarget("PB_LowCalMag", 20);
			#### # 0 A_Jump(256,"Waits");
		GiveHealth:
			PLAY A 10 A_FaceTarget;
			PLAY B 30 A_StartVoiceLine("MRNGI2");
			goto HandOverStimpack;
		HandOverStimpack:
			#### # 0 A_GiveToTarget("PB_Stimpack");
			#### # 0 A_Jump(256,"Waits");
		Salute:
			#### # 0 A_Jump(255, "Salutes1", "Salutes2");
		Salutes1:
			MWAV B 6 A_PlaySound ("DSSALUTE");
			MWAV CDEFEFDCB 6;
			#### # 0 A_Jump(256,"FollowPlayer");
		Salutes2:
			MWAV G 8 A_PlaySound ("DSSALUTE");
			MWAV HGHG 8;
			#### # 0 A_Jump(256,"FollowPlayer");
	}
}