extend class PBMarine{
	States{
		MissileBackup:
			#### # 0 A_Jump(256,"Missile.Rifle","Missile.Pistol");
		Missile.Rifle:
			PLAY E 6 A_FaceTarget;
			#### # 0 A_JumpIf(random(0,2)>1 && CheckTargetSurroundingAllies(220)<1 && CheckTargetSurroundingEnemies(220)>3,"AttackGrenade");
			#### # 0 A_Jump(128,2);
			#### # 0 A_JumpStrafe;
			PLAY E 6 A_FaceTarget;
			#### # 0 A_AllyAlertMonsters(1000,AMF_TARGETEMITTER);
			PLAY F 3 BRIGHT {if(!D_AbortAndReloadIfEmpty("PB_DMR")){D_DepleteWeaponAmmo("PB_DMR");A_CustomMissile("PBMarineMuzzle1",34);A_PlaySound("weapons/rifle");A_SpawnProjectile("PBMarine_556x45mm", 40, 0, 0, 0);PB_SpawnCasing("EmptyBrass",28,0,30,3,Frandom(5,8),Frandom(1,4));}}
			PLAY E 3 A_FaceTarget;
			PLAY F 3 BRIGHT {if(!D_AbortAndReloadIfEmpty("PB_DMR")){D_DepleteWeaponAmmo("PB_DMR");A_CustomMissile("PBMarineMuzzle1",34);A_PlaySound("weapons/rifle");A_SpawnProjectile("PBMarine_556x45mm", 40, 0, 0, 0);PB_SpawnCasing("EmptyBrass",28,0,30,3,Frandom(5,8),Frandom(1,4));}}
			PLAY E 3 A_FaceTarget;
			PLAY F 3 BRIGHT {if(!D_AbortAndReloadIfEmpty("PB_DMR")){D_DepleteWeaponAmmo("PB_DMR");A_CustomMissile("PBMarineMuzzle1",34);A_PlaySound("weapons/rifle");A_SpawnProjectile("PBMarine_556x45mm", 40, 0, 0, 0);PB_SpawnCasing("EmptyBrass",28,0,30,3,Frandom(5,8),Frandom(1,4));}}
			TNT1 J 0 A_Jump(256,"See");
		Missile.Pistol:
			PLAY E 6 A_FaceTarget;
		Missile.Pistol.Continue:
			#### # 0 A_AllyAlertMonsters(1000,AMF_TARGETEMITTER);
			PLA2 F 3 BRIGHT {if(!D_AbortAndReloadIfEmpty("PB_Pistol")){A_PlaySound("weapons/pistol", 1);PB_SpawnCasing("EmptyBrassPistol",26,9,38,Frandom(-2,2),-Frandom(2,5),Frandom(3,6));D_DepleteWeaponAmmo("PB_Pistol");A_SpawnProjectile("PBMarine_45ACPHP", 32, 0, 0, 1, 0);}}
			PLA2 E random(0,9) A_FaceTarget;
			#### # 0 A_JumpIfCloser(600,2);
			#### # 0 A_Jump(256,"See");
			#### # 0 A_MarineRefire(40);
			#### # 0 A_Jump(256,"Missile.Pistol.Continue");
		AttackGrenade:
			PLA1 A 1 A_StartSound("OPNGRN",CHAN_AUTO);
			PLA1 ABBCCDDAA 1 A_FaceTarget;
			MRGL E 6 BRIGHT {A_StartSound("THRGRN",CHAN_AUTO);A_SpawnGravityProjectile("MarineThrownGrenade");}
			#### # 0 A_Jump(256,"Retreat");
	}
}