extend class PBMarine{
	States{
		MarineSequence:
			#### # 1;
			#### # 0 A_ChangeFlag("NODROPOFF", 1);
			#### # 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");
			#### # 0 A_JumpIfTargetIsPlayer("CheckRangeToWait");
			#### # 0 A_Jump(256,"See");
		MarineSequenceGuarding:
			#### # 1;
			#### # 0 A_ChangeFlag("NODROPOFF", 1);
			#### # 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "ForgetTarget");
			#### # 0 A_JumpIfTargetIsPlayer("ForgetTarget");
			#### # 0 A_Jump(256,"See");
		Missile:
			#### # 1;
			#### # 0 A_JumpIf(speed == 0,"Missile.Guarding");
			#### # 0 A_DebugLog("Missile Sequence");
			#### # 0 {A_ChangeFlag("NODROPOFF", 1);A_SpawnItem("KillMeSmall");}
			#### # 0 A_JumpIf(CheckTargetSpecies("Mastermind")||CheckTargetClass("SpiderMastermind")||CheckTargetClass("PB_Mastermind")||
					CheckTargetSpecies("CyberDemon")||CheckTargetClass("CyberDemon")||CheckTargetClass("PB_Cyberdemon")||
					CheckTargetSpecies("BigFatAss")||CheckTargetClass("PB_Mancubus")||CheckTargetClass("Fatso")||
					CheckTargetClass("BaronofHell")||CheckTargetClass("PB_Baron"),"CheckRetreat");
			#### # 0 A_JumpIfTargetIsMarine("FollowPlayer");
			#### # 0 A_JumpIfTargetIsPlayer("CheckRangeToWait");
			#### # 0 A_MakeShootable();
			#### # 0 A_ChangeFlag("SOLID", 1);
			
			#### # 0 A_JumpIf(!(self is "Marine_Rifle" || self is "Marine_HDMR" || self is "Marine_Carbine" || self is "Marine_SMG"),2);
			#### # 0 A_JumpIfCloser(60, "AttackMelee");
			#### # 0 A_Jump(256,2);
			#### # 0 A_JumpIfCloser(60, "AttackKick");
			
			#### # 0 A_JumpIfCloser(300, "Retreat");
			#### # 0 A_StartVoiceLine("MRNAT", 2);
			#### # 0 A_JumpIf(random(0,2)>1 && CheckTargetSurroundingAllies(220)<1 && CheckTargetSurroundingEnemies(220)>3,"AttackGrenade");
			#### # 0 A_Jump(256,"Missile2");
		AttackGrenade:
			PLA1 H 10 D_DoMarineFireFX("MarineFragThrow",10);
			PLA1 E 6 ;
			#### # 0 A_Jump(256,"Retreat");
			#### # 0 A_JumpIf(!(self is "Marine_Rifle" || self is "Marine_HDMR" || self is "Marine_Carbine" || self is "Marine_SMG"),"Missile2");
			#### # 0 A_JumpStrafeChance(128);
			#### # 0 A_Jump(256,"Missile2");
		Missile.Guarding:
			#### # 0 A_DebugLog("Missile.Guarding Sequence");
			#### # 0 {A_ChangeFlag("FRIENDLY", 1);A_SpawnItem("KillMeSmall");}
			#### # 0 A_JumpIf(CheckTargetSpecies("Mastermind")||CheckTargetClass("SpiderMastermind")||CheckTargetClass("PB_Mastermind")||
					CheckTargetSpecies("CyberDemon")||CheckTargetClass("CyberDemon")||CheckTargetClass("PB_Cyberdemon"),"CheckRetreat");
			#### # 0 A_JumpIfTargetIsMarine("Spawn");
			#### # 0 A_MakeShootable();
			#### # 0 A_ChangeFlag("SOLID", 1);
			#### # 0 A_StartVoiceLine("MRNAT", 2);
			#### # 0 A_Jump(256,"Missile2");
			
		Melee:
			#### # 1 A_DebugLog("Melee Sequence");
			#### # 0 A_ChangeFlag("NODROPOFF", 1);
			#### # 0 A_SpawnItem("KillMeSmall");
			
			#### # 0 A_JumpIf(CheckTargetSpecies("Mastermind")||CheckTargetClass("SpiderMastermind")||CheckTargetClass("PB_Mastermind")||
				CheckTargetSpecies("CyberDemon")||CheckTargetClass("CyberDemon")||CheckTargetClass("PB_Cyberdemon")||
				CheckTargetSpecies("BigFatAss")||CheckTargetClass("PB_Mancubus")||CheckTargetClass("Fatso")||
				CheckTargetClass("BaronofHell")||CheckTargetClass("PB_Baron"),"CheckRetreat");
			
			#### # 0 A_JumpIfTargetIsMarine("FollowPlayer");
			#### # 0 A_JumpIfTargetIsPlayer("CheckRangeToWait");
			#### # 0 A_ChangeFlag("SHOOTABLE", 1);
			#### # 0 A_ChangeFlag("SOLID", 1);
			#### # 0 A_JumpIfCloser(60, "AttackMelee");
			#### # 0 A_JumpIfCloser(300, "Retreat");
			#### # 1 A_Jump(256,"AttackMelee");
		AttackMelee:
			---- A 0 A_Jump(32, "AttackKick");
		AttackPunch:
			PLAM A 4 {PBMarine_Execute();A_FaceTarget();}
			PLAM A 1 {A_Recoil(-4);A_FaceTarget();}
			goto DoAttackPunch;
		DoAttackPunch:
			#### # 0 {
				if(FindInventory("PB_PowerStrength")){
					A_CustomMissile("MarineMeleeStrike",40,0,0,0);
				}
				else{
					A_CustomMissile("MarineMeleeStrikeSuper",40,0,0,0);
				}
			}
			#### # 0 A_Jump(256,"FinishAttackPunch");
		FinishAttackPunch:
			PLAM B 6 ;
			#### # 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
			#### # 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
			#### # 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			#### # 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
			#### # 0 A_Jump(256,"See");
		AttackKick:
			"####" A 1 {PBMarine_Execute();A_FaceTarget();}
			---- A 0 {ThrustThingZ(0,40,0,1);A_Recoil(-8);}
			MARJ A 6 A_FaceTarget;
			goto DoAttackKick;
		DoAttackKick:
			#### # 0 {
				if(FindInventory("PB_PowerStrength")){
					A_CustomMissile("MarineKickAttack",40,0,0,0);
				}
				else{
					A_CustomMissile("MarineSuperKickAttack",40,0,0,0);
				}
			}
			#### # 0 A_Jump(256,"FinishAttackKick");
		FinishAttackKick:
			PKIK A 1 ;
			PKIK A 6 A_Stop;
			#### # 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
			#### # 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
			#### # 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			#### # 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
			#### # 0 A_Jump(256,"See");
			
		Missile.NoFire:
			#### # 1 A_DebugLog("Missile.NoFire Sequence");
			#### # 0 A_ChangeFlag("NODROPOFF", 1);
			#### # 0 A_JumpIf(CheckTargetSpecies("Mastermind")||CheckTargetClass("SpiderMastermind")||CheckTargetClass("PB_Mastermind")||
				CheckTargetSpecies("CyberDemon")||CheckTargetClass("CyberDemon")||CheckTargetClass("PB_Cyberdemon")||
				CheckTargetSpecies("BigFatAss")||CheckTargetClass("PB_Mancubus")||CheckTargetClass("Fatso")||
				CheckTargetClass("BaronofHell")||CheckTargetClass("PB_Baron"),"CheckRetreat");
			#### # 0 A_JumpIfTargetIsMarine("FollowPlayer");
			#### # 0 A_JumpIfTargetIsPlayer("CheckRangeToWait");
			#### # 0 A_ChangeFlag("SHOOTABLE", 1);
			#### # 0 A_ChangeFlag("SOLID", 1);
			#### # 0 A_JumpIfCloser(60, "AttackKick");
			#### # 0 A_JumpIfCloser(300, "Retreat");
			#### # 0 A_ChangeFlag("SHOOTABLE", 0);
			#### # 0 A_ChangeFlag("SOLID", 0);
			#### # 0 A_Jump(128,"See");
			#### # 0 A_JumpStrafe;
			#### # 0 A_Jump(256,"See");
	}
}