extend class PBMarine{
	States{
		Waits:
			---- A 0 {
				let def = GetDefaultByType(self.GetClass());
				if(def){
					self.sprite = def.spawnstate.sprite;
					self.frame = def.spawnstate.frame;
				}
				D_StartReloadIfEmpty();
			}
			#### A 1 D_StartReloadIfNotFullIdle;
			---- A 0 A_JumpIfTargetIsPlayer(3);
			---- A 0 A_ClearTarget();
			---- A 0 A_Jump(256,"See");
			---- A 0 A_ChangeFlag("FRIENDLY", 0);
			---- A 0 A_ChangeFlag("MISSILEMORE", 1);
			---- A 0 A_ChangeFlag("MISSILEEVENMORE", 1);
			---- A 0 A_MakeNotShootable();
			---- A 0 A_ChangeFlag("SOLID", 0);
			---- A 0 A_JumpIfTargetIsMarine("BecomeEnemy23");
			---- A 0 A_Jump(32, "Waits2");
			---- A 0 A_Jump(32, "Waits3");
			#### AA 8 A_Stop;
			---- A 0 A_Stop;
			---- A 0 A_CheckSight("FollowPlayer");
			---- A 0 {A_ChangeFLag("FRIENDLY", 1);A_ClearTarget();A_MakeShootable();}
			---- A 0 A_Look;
			---- A 0 {A_ChangeFLag("FRIENDLY", 0);A_MakeNotShootable();}
			#### A 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
			---- A 0 A_CheckSIght("FollowPlayer");
			---- A 0 A_MakeShootable();
			---- A 0 A_JumpIfCloser(200, "Waits");
			---- A 0 A_Jump(256,"FollowPLayer");
		Waits2:
			---- A 0 {
				let def = GetDefaultByType(self.GetClass());
				if(def){
					self.sprite = def.spawnstate.sprite;
					self.frame = def.spawnstate.frame;
				}
				D_StartReloadIfEmpty();
			}
			---- A 0 A_SetAngle(random(90, -90) + angle);
			#### A 8 A_Stop;
			---- A 0 A_StartVoiceLine("MRNWT", 2);
			#### A 8 A_Stop;
			---- A 0 A_CheckSight("FollowPlayer");
			---- A 0 {A_ChangeFLag("FRIENDLY", 1);A_ClearTarget();A_MakeShootable();}
			---- A 0 A_Look;
			---- A 0 {A_ChangeFLag("FRIENDLY", 0);A_MakeNotShootable();}
			#### A 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
			---- A 0 A_CheckSIght("FollowPlayer");
			---- A 0 A_MakeShootable();
			---- A 0 A_JumpIfCloser(300, "Waits");
			---- A 0 A_Jump(256,"FollowPLayer");
		Waits4:
			---- A 0 {
				let def = GetDefaultByType(self.GetClass());
				if(def){
					self.sprite = def.spawnstate.sprite;
					self.frame = def.spawnstate.frame;
				}
				D_StartReloadIfEmpty();
			}
			---- A 0 A_SetAngle(random(90, -90) + angle);
			#### A 8 A_Stop;
			---- A 0 A_StartVoiceLine("MRNWC", 2);
			#### A 8 A_Stop;
			---- A 0 A_CheckSight("FollowPlayer");
			---- A 0 {A_ChangeFLag("FRIENDLY", 1);A_ClearTarget();A_MakeShootable();}
			---- A 0 A_Look;
			---- A 0 {A_ChangeFLag("FRIENDLY", 0);A_MakeNotShootable();}
			#### A 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
			---- A 0 A_CheckSIght("FollowPlayer");
			---- A 0 A_MakeShootable();
			---- A 0 A_JumpIfCloser(300, "Waits");
			---- A 0 A_Jump(256,"FollowPLayer");
	}
}