extend class PBMarine{
	States{
	Crush:
		CRS1 A 5 A_PlaySound("misc/xdeath4");
		CRS1 A -1;
		Stop;
	Death:
	Death.Bullet:
		PLAY H 10 {A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));A_ChangeFlag("FRIENDLY", 0);A_ChangeFlag("USESPECIAL", 0);A_PlayerScream();}
		PLAY I 10 A_NoBlocking();
		PLAY JKLM 10;
		#### N -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.Eat:
		XPL1 A 10 {A_GiveToTarget("EatMe",1);A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));A_XScream();}
		XPL1 B 20 A_NoBlocking();
		XPL1 CDE 10 ;
		XPL1 E -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.Cut:
	Death.Saw:
		#### # 0 {
			A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 A_NoBlocking();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 E -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.Slime:
		#### # 0 A_PlaySound("BIGSCREA");
		PMET AABBCCDDEEFFGGHHIIIII 10 A_CustomMissile("PlasmaSmoke", 25, 0, random (0, 180), 2, random (0, 180));
		PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 A_CustomMissile("PlasmaSmoke", 25, 0, random (0, 180), 2, random (0, 180));
		#### # -1 A_NoBlocking();
		Stop;
	Death.CutLess:
		#### # 0 A_Jump (128, 1);
		Goto Death;
		#### # 0 {
			A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 A_NoBlocking();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 E -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.Rip:
		TNT1 AAAAAAAAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 A 10 A_XScream();
		TNT1 AAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 B 20 A_NoBlocking();
		#### # 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		#### # 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 D 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		#### # 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 E 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		#### # 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		#### # 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.Massacre:
	Death.Explosives:
	XDeath:
		MHEA A 7 {
			ThrustThingZ(0,60,0,1);
			A_CustomMissile("MarineXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			A_SpawnItemEx("BasicMarineGib2", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			A_SpawnItemEx("BasicMarineGib3", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			A_SpawnItemEx("BasicMarineGib4", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			A_XScream();
		}
		MHEA B 7 A_NoBlocking();
		MHEA CD 7;
		MHEA E -1;
		Stop;
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile("Brutal_FlyingBloodTrail8", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 {A_CustomMissile("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));A_CustomMissile("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));}
		TNT1 AA 0 {A_CustomMissile("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));A_CustomMissile("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));}
		TNT1 A 1 {A_SpawnItem("GrowingBloodPool");A_SpawnItem("CrushedRemains");}
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
		Stop;
	Death.Blast:
	Death.SuperPunch:
	Death.SSG:
		PLAY O 2 A_FaceTarget;
		TNT1 AAAA 0 {
			A_CustomMissile("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_CustomMissile("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		}
		#### # 0 A_CustomMissile("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		#### # 0 A_XScream();
		#### # 0 A_NoBlocking();
		PLAY OPQRSTU 8;
		#### # 0 A_SpawnItem("MediumBloodSpot");
		PLAY U -1;
		Stop;
	Death.Destruction:
		TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 A 20 A_XScream();
		#### # 0 {A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));}
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 B 20 A_NoBlocking();
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 C 20;
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 D 20;
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 E 20;
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 F 20;
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		#### # 0 A_SpawnItem("MediumBloodSpot");
		XPL4 F -1;
		Stop;
	Death.plasma:
		#### # 0 {A_XScream();A_NoBlocking();}
		---- AAA 0 A_CustomMissile("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		#### # 0 {
			A_CustomMissile("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		}
		EXPL AAAAAA 0 A_CustomMissile("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
		#### # 1;
		#### # -1;
		Stop;
	Death.Minigun:
		#### # 0 A_Jump (128, 1);
		Goto Death;
		#### # 0 {
			A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 A_NoBlocking();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 E -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.GreenFire:
		#### # 0 {A_XScream();A_NoBlocking();}
		TNT1 AAAA 0 A_CustomMissile("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		#### # 0 {
			A_CustomMissile("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		}
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
		Stop;
	Death.burn:
		PBUR A 1;
		PBUR A 1 A_Scream();
		PBUR A 1 A_NoBlocking();
		PBUR AAAABBBBCCCC 2 A_CustomMissile("SmallFlameTrails", 32, 0, random (0, 180), 2, random (0, 180));
		PBUR DDDDEEEE 2 A_CustomMissile("SmallFlameTrails", 16, 0, random (0, 180), 2, random (0, 180));
		PBUR EEEEE 4 A_CustomMissile("SmallFlameTrails", 8, 0, random (0, 180), 2, random (0, 180));
		PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		PBUR E -1;
		Stop;
	Death.Fire:
	Death.Flames:
	Death.Burn:
		BURN W 6 {A_PlaySound("BIGSCREA");A_Scream();}
		BURN X 6 A_NoBlocking();
		BUR2 ABCD 6 BRIGHT A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN FGHIJKL 6 BRIGHT A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN MNOPQRSTUV 6 BRIGHT A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 6 A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN V -1;
		Stop;
	Death.ExplosiveImpact:
		NULL A 0 {
			ThrustThingZ(0,30,0,1);
			A_CustomMissile("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("Brains4", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
			A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		}
		NULL AAAA 0 {
			A_CustomMissile("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
			A_CustomMissile("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		}
		NULL AA 0 A_CustomMissile("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		NULL AAAAAAAAAAA 0 A_CustomMissile("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL6 A 5 A_XScream();
		XPL6 B 5 A_NoBlocking();
		XPL6 CDE 5;
		XPL6 F -1;
		Stop;
	Death.Rape:
		TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 A 20 A_XScream();
		#### # 0 {
			A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 B 20 A_NoBlocking();
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 C 20;
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 D 20;
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 E 20;
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 F 20;
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 F -1 A_SpawnItem("MediumBloodSpot");
		Stop;
	Death.HKFT:
	Death.BHFT:
	Death.RVFT:
		#### # 1 A_Scream();
		#### # 1 A_NoBlocking();
		#### # 0 A_GiveToTarget("Curbstomp_Marine",1);
		//#### # -1;
		Stop;
	Death.FatalityMarine:
		#### # 1 A_PlayerScream;
		#### # 1 {A_NoBlocking();A_GiveToTarget("GoFatality", 1);}
		#### # -1 A_GiveToTarget("Fatality_Marine",1);	
		Stop;
	}
}