class MarineShotgunPump : MarineDelayFireFX{
	States{
	Spawn:
		SHTF B 1 ;
		SHTF C 14 {master.A_CustomMissile("ShotgunWad",32);}
		SHTG K 1 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		TNT1 A 15 {PB_SpawnCasing("ShotgunCasing",15,-5,26,0,3,3);}
		stop;
	}
}
class MarineGLFireDelay : MarineDelayFireFX{
//delayFireFx
	States{
	Spawn:
		MRGL A 1 NODELAY ;
		MRGL A 2 PB_SpawnCasing("EmptyGrenadeBrass", 30, 0, 34, -frandom(1, 3), -frandom(2, 4), 5);
		TNT1 A 14 {master.bBRIGHT=false;master.A_FaceTarget();master.A_StartSound("RLCYCLE2", 13);}
		TNT1 A 8 {master.A_StartSound("weapons/sgl/cycle", 9);}
		TNT1 A 0 A_JumpIfShotCounter("Spawn");
		stop;
	}
}
class MarineRLFireDelay : MarineDelayFireFX{
	States{
	Spawn:
		MRGL A 2 NODELAY {PBM_MuzzleFlash("PBMarineMuzzle1",50);A_AllyAlertMonsters(500,AMF_TARGETEMITTER);}
		MRGL A 4 {master.bBRIGHT=false;master.A_FaceTarget();}
		TNT1 A 0 A_JumpIf(D_AbortAndReloadIfEmpty(null,null,1,null),"Firing_Empty");
		goto Firing_Normal_Single;
	Firing_Normal_Single:
		TNT1 A 7 {master.A_StartSound("weapons/rocket/innercycle", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 5 {master.A_StartSound("RLCYCLE2", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 9 {master.A_StartSound("weapons/rocket/loadingmechanism2", 1);}
		goto FireFinish;
	Firing_Empty:
		TNT1 A 21;
		goto FireFinish;
	FireFinish:
		TNT1 A 0 A_JumpIfShotCounter("Spawn");
		stop;
	}
}
class MarineShotgunPumpSlug : MarineDelayFireFX{
	States{
	Spawn:
		SHTF B 1 ;
		SHTF C 14 {master.A_CustomMissile("ShotgunWad",32);}
		SHTG K 1 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		TNT1 A 15 {PB_SpawnCasing("ShotgunCasing3",15,-5,26,0,3,3);}
		stop;
	}
}
class MarineAutoShotgunPump : MarineDelayFireFX{
	States{
	Spawn:
		AG40 A 5;
		AG40 A 8;
		TNT1 A 15 {master.A_PlaysoundEx("H4SGCOCK", "Auto");}
		stop;
	}
}
class MarineNailgunAltfireSequence : MarineDelayFireFX{
	States{
	Spawn:
		N5N0 WXY 1;
		N8N0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1;
		stop;
	}
}
class MarineNailgunJavelinSequence : MarineDelayFireFX{
	States{
	Spawn:
		PLSG JKLKJ 1 ;
		J1N0 GHIJKLMN 1;
		TNT1 A 2 {master.A_StartSound("weapons/nailgun/inspect2", CHAN_AUTO);}
		TNT1 A 10 {master.A_StartSound("weapons/nailgun/loadjavelin", CHAN_AUTO);}
		J2N0 ABCDEFGH 1;
		J0N0 D 14 ;
		stop;
	}
}
class MarinePlasmaCoolDown : MarineDelayFireFX{
	States{
	Spawn:
		PLSG JKLKJ 1 ;
		PLSU BCDE 1;
		TNT1 A 0 {master.A_StartSound("PLSCOOL",CHAN_VOICE);}
		PLSU FFFFFFFFF 2 A_SpawnProjectile("SmokeSpawner",32);
		PLSG DCB 1;
		stop;
	}
}
class MarineRailgunRecoil : MarineDelayFireFX{
	States{
	Spawn:
		TNT1 A 37;
		stop;
	}
}
class MarineDemonTechWeaponCooldown : MarineDelayFireFX{
	States{
	Spawn:
		TNT1 A 15 NODELAY {master.A_PlaySoundEx("HRSteam", "Auto");}
		stop;
	}
}//
class MarineDemonTechWeaponSpecial : MarineDelayFireFX{
	States{
	Spawn:
		TNT1 A 4 NODELAY {master.A_PlaySoundEx("weapons/demontech/weaponspecial1", "Auto");}
		TNT1 A 20 {master.A_PlaySoundEx("weapons/demontech/weaponspecial2", "Auto");}
		stop;
	}
}