/*
	class<Ammo> AmmoTypeLeft;
	Ammo AmmoLeft;
*/
class MarinePistolReload : MarineReloadFX{
	States{
	Spawn:
		D5GB A 4;
		TNT1 A 7 {master.A_PlaySoundEx("PSRLOUT", "Auto");}
		TNT1 A 3 PB_SpawnCasing("EmptyClipMP40",28,0,30,3,Frandom(-8,-5),Frandom(1,4));
		TNT1 A 15 {master.A_PlaySoundEx("PSRLIN", "Auto");}
		TNT1 A 17 {master.A_PlaySoundEx("PSRLFIN", "Auto");}
		stop;
	}
}
class MarinePistolReload2 : MarineReloadFX{
	States{
	Spawn:
		D5GB A 4;
		TNT1 A 7 {master.A_PlaySoundEx("PSRLOUT", "Auto");}
		TNT1 A 3 ;//PB_SpawnCasing("EmptyClipMP40",28,0,30,3,Frandom(-8,-5),Frandom(1,4));
		TNT1 A 15 {master.A_PlaySoundEx("PSRLIN", "Auto");}
		stop;
	}
}
class MarineRevolverReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		TNT1 A 6 NODELAY {master.A_PlaySound("Ironsights");}
		TNT1 A 10 {master.A_PlaySoundEx("Weapons/Revolver/Open", "Auto");}
		TNT1 A 4 {master.A_PlaySoundEx("Weapons/Revolver/Click2", "Auto");}
		TNT1 AAAAAA 0 {
			//master.A_SpawnProjectile("MagnumCasing",-5,0,0,-30);//PB_RevolverCasingSpawn("RevolverAmmo")
			PB_SpawnCasing("MagnumCasing", 45.6, 9, 18.75,frandom(-0.5,0.5),frandom(-0.4, -0.2), frandom(0.5,-0.5));
		}
		R6V1 A 7;
		R6V2 A 7 {master.A_PlaySoundEx("Weapons/Revolver/Load", "Auto");}
		TNT1 A 3 {
			master.A_PlaySoundEx("CYLNSPIN", "Auto");
			PB_SpawnCasing("RevolverSpeedLoader", 45.6, 9, 18.75,frandom(-1,1),frandom(-1.2, -0.6), frandom(1,-1));
		}
		TNT1 A 9 {master.A_PlaySoundEx("Weapons/Revolver/Close", "Auto");}
		stop;
	}
}
class MarineRevolverReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		TNT1 A 6 NODELAY {master.A_PlaySound("Ironsights");}
		TNT1 A 10 {master.A_PlaySoundEx("Weapons/Revolver/Open", "Auto");}
		TNT1 A 4 {master.A_PlaySoundEx("Weapons/Revolver/Click2", "Auto");}
	LoadLoop:
		TNT1 A 0 {
			//master.A_SpawnProjectile("MagnumCasing",-5,0,0,-30);//PB_RevolverCasingSpawn("RevolverAmmo")
			PB_SpawnCasing("MagnumCasing", 45.6, 9, 18.75,frandom(-0.5,0.5),frandom(-0.4, -0.2), frandom(0.5,-0.5));
		}
		R6V1 A 7 A_JumpIfReloadCounter("LoadLoop");
		R6V2 A 7 {master.A_PlaySoundEx("Weapons/Revolver/Load", "Auto");}
		TNT1 A 3 {
			master.A_PlaySoundEx("CYLNSPIN", "Auto");
			PB_SpawnCasing("RevolverSpeedLoader", 45.6, 9, 18.75,frandom(-1,1),frandom(-1.2, -0.6), frandom(1,-1));
		}
		TNT1 A 9 {master.A_PlaySoundEx("Weapons/Revolver/Close", "Auto");}
		stop;
	}
}
class MarineDeagleReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		TNT1 A 0 NODELAY A_JumpIfReloadCounter("Reload2");
		D1E0 ABCDEFG 1;
		D1E0 H 1 {A_PlaySoundEx("weapons/deagle/magout", "Auto");A_PlaySoundEx("PSRLOUT", "Auto");}
		D1E0 IJKLM 1 ;
		D1E0 N 3 A_CustomMissile("EmptyDeagleMag",5,0,12,-4);
		D1E0 OP 1 ;
		D1E0 Q 1 {A_PlaySoundEx("weapons/deagle/magin", "Auto");A_PlaySoundEx("RIFCL_IN", "Auto");}
		D1E0 RSTUVWXY 1;
		D1E0 Z 1 A_PlaySoundEx("weapons/deagle/click1", "Auto");
		D1E1 ABCD 1;
		D1E1 D 1 A_PlaySoundEx("weapons/deagle/click2", "Auto");
		D1E1 EFGHIJKL 1;
		stop;
	Reload2:
		D0E0 ABCDEFGHIIIIJKL 1;
		D0E0 M 1 {A_PlaySoundEx("weapons/deagle/magout", "Auto");A_PlaySoundEx("PSRLOUT", "Auto");}
		D0E0 NO 1;
		D1E2 N 3 A_PlaySoundEx("Ironsights", "Auto");
		D1E2 P 3;
		D1E2 Q 1 {A_PlaySoundEx("weapons/deagle/magin", "Auto");A_PlaySoundEx("RIFCL_IN", "Auto");}
		D1E2 RSTUV 1;
		D1E1 EFGHIJKL 1;
		stop;
	}
}
class MarineDeagleReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		D0E0 ABCDEFGHIIIIJKL 1;
		D0E0 M 1 {A_PlaySoundEx("weapons/deagle/magout", "Auto");A_PlaySoundEx("PSRLOUT", "Auto");}
		D0E0 NO 1;
		D1E2 N 3 A_PlaySoundEx("Ironsights", "Auto");
		D1E2 P 3;
		D1E2 Q 1 {A_PlaySoundEx("weapons/deagle/magin", "Auto");A_PlaySoundEx("RIFCL_IN", "Auto");}
		D1E2 RSTUV 1;
		D1E1 EFGHIJKL 1;
		stop;
		D1E0 ABCDEFG 1;
		D1E0 H 1 {A_PlaySoundEx("weapons/deagle/magout", "Auto");A_PlaySoundEx("PSRLOUT", "Auto");}
		D1E0 IJKLM 1 ;
		D1E0 N 3 A_CustomMissile("EmptyDeagleMag",5,0,12,-4);
		D1E0 OP 1 ;
		D1E0 Q 1 {A_PlaySoundEx("weapons/deagle/magin", "Auto");A_PlaySoundEx("RIFCL_IN", "Auto");}
		D1E0 RSTUVWXY 1;
		D1E0 Z 1 A_PlaySoundEx("weapons/deagle/click1", "Auto");
		D1E1 ABCD 1;
		D1E1 D 1 A_PlaySoundEx("weapons/deagle/click2", "Auto");
		D1E1 EFGHIJKL 1;
		stop;
	}
}
class MarineSMGReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 37;
	}
	States{
	Spawn:
		/*
		A1F0 A 5;
		TNT1 A 5 {master.A_StartSound("RIFCL_CK", CHAN_AUTO);}
		A1F0 K 4 {master.A_StartSound("weapons/mar/smg_out", CHAN_AUTO);}
		TNT1 A 2 {master.A_StartSound("weapons/mar/smg_up", CHAN_AUTO);}
		TNT1 A 14 PB_SpawnCasing("SMGEmptyMagazine",28,0,30,3,Frandom(-8,-5),Frandom(1,4));
		A2F4 A 7 {master.A_StartSound("weapons/mar/smg_in", CHAN_AUTO);}
		TNT1 A 5 {master.A_PlaySoundEx("IronSights", "Auto");}
		TNT1 A 5 {master.A_PlaySoundEx("weapons/mar/smg_click", "Auto");}
		A2F4 A 9;
		stop;
	NewReload:
		*/
		TNT1 A 2 NODELAY A_StartSound("weapons/smg/raise");
		TNT1 A 0 A_JumpIfReloadPartial("ReloadPartial");
		goto BoltPull;
	BoltPull:
		TNT1 A 2 A_StartSound("weapons/smg/raise");
		TNT1 A 6 A_StartSound("weapons/smg/armup", CHAN_AUTO);
		TNT1 A 11 A_StartSound("weapons/smg/boltlock", CHAN_AUTO);
		Goto ReloadEmpty;
	ReloadPartial:
		TNT1 A 2;
		TNT1 A 7 A_StartSound("weapons/rifle/magchange", CHAN_AUTO);
		TNT1 A 16 A_StartSound("weapons/smg_out", CHAN_AUTO);
		Goto ReloadContinue;
	ReloadEmpty:
		TNT1 A 1;
		TNT1 A 7 A_StartSound("weapons/rifle/magchange", CHAN_AUTO);
		TNT1 A 16 A_StartSound("weapons/smg_out", CHAN_AUTO);
		TNT1 A 0 PB_SpawnCasing("SMGEmptyMagazine",28,0,30,3,Frandom(-8,-5),Frandom(1,4));
	ReloadContinue:
		TNT1 A 5 A_StartSound("weapons/smg/tilt");
		TNT1 A 1 A_PlaySoundEx("weapons/smg_in", "Auto");
	InsertBullets2:
		TNT1 A 6 A_JumpIfReloadPartial("LoadChamber");
		TNT1 A 6 A_StartSound("weapons/smg/lower");
	LoadChamber:
		TNT1 A 12;
		TNT1 A 5 A_StartSound("weapons/smg/armswing", CHAN_AUTO);
		TNT1 A 17 A_PlaySoundEx("weapons/smg_click", "Auto");
		stop;
	}
}
class MarineSMGReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 37;
	}
	States{
	Spawn:
		A1F0 A 10;
		A1F0 K 4 {master.A_StartSound("weapons/mar/smg_out", CHAN_AUTO);}
		TNT1 A 16 {master.A_StartSound("weapons/mar/smg_up", CHAN_AUTO);}
		A2F4 A 7 {master.A_StartSound("weapons/mar/smg_in", CHAN_AUTO);}
		TNT1 A 5 {master.A_PlaySoundEx("IronSights", "Auto");}
		TNT1 A 14 ;
		stop;
	AltReload:
		stop;
	}
}
class MarineShotgunReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		SHTG A 11;
		SSHR H 2 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		SSHR I 11 {master.A_PlaySoundEx("insertshell","Auto");}
		SSHR A 4 {master.A_PlaySoundEx("weapons/sgpump","Auto");}
		SSHR EEEEEEEE 7 {master.A_PlaySoundEx("insertshell", "Auto");}
		SSHR E 7;
		//SSHR E 3 {master.A_PlaySoundEx("insertshell", "Auto");}
		stop;
	}
}
class MarineShotgunReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		SHTG A 11;
	LoadLoop:
		SSHR E 7 {master.A_PlaySoundEx("insertshell", "Auto");}
		TNT1 AA 0 A_JumpIfReloadCounter("LoadLoop");
		SSHR E 8;
		stop;
	}
}
class MarineShotgunMagReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		SHTG A 11;
		SSHR H 2 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		SSHR I 11 {master.A_PlaySoundEx("insertshell","Auto");}
		TNT1 A 6 {master.A_PlaySoundEx("weapons/shotgunmag/magout", "Auto");}
		TNT1 A 10 PB_SpawnCasing("EmptyClipMP40",28,0,30,3,Frandom(-8,-5),Frandom(1,4));//A_FireCustomMissile("EmptyClipMP40",-5,0,8,-4)
		SHTM H 7 {master.A_PlaySoundEx("weapons/shotgunmag/magin", "Auto");}
		SHTM H 12 ;
		SSHR A 4 {master.A_PlaySoundEx("weapons/sgpump","Auto");}
		SSHR E 8;
		stop;
	}
}
class MarineShotgunMagReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		SHTG A 11;
		TNT1 A 6 {master.A_PlaySoundEx("weapons/shotgunmag/magout", "Auto");}
		TNT1 A 10 PB_SpawnCasing("EmptyClipMP40",28,0,30,3,Frandom(-8,-5),Frandom(1,4));//A_FireCustomMissile("EmptyClipMP40",-5,0,8,-4)
		SHTM H 7 {master.A_PlaySoundEx("weapons/shotgunmag/magin", "Auto");}
		SHTM H 12 ;
		SSHR E 8;
		//SSHR E 3 {master.A_PlaySoundEx("insertshell", "Auto");}
		stop;
	}
}
class MarineSSGReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		TNT1 A 7 ;
		TNT1 AA 0 {master.A_SpawnItem("SSGCaseSpawner", 0, 30,0);}
		TNT1 E 10 {master.A_PlaySound("weapons/ssg/open");}
		TNT1 E 5 {master.A_playsound("weapons/ssg/inspect2");}
		TNT1 E 4 {master.A_PlaySound("weapons/ssg/inspect3");}
		stop;
	}
}
class MarineSSGReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 26;
	}
	States{
	Spawn:
		TNT1 A 7 ;
		TNT1 E 10 {master.A_SpawnItem("SSGCaseSpawner", 0, 30,0);master.A_PlaySound("weapons/ssg/open");}
		TNT1 E 5 {master.A_playsound("weapons/ssg/inspect2");}
		TNT1 E 4 {master.A_PlaySound("weapons/ssg/inspect3");}
		stop;
	}
}
class MarineASGReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 37;
	}
	States{
	Spawn:
		TNT1 A 4 NODELAY {master.A_PlaysoundEx("Ironsights", "Auto");}
		AG31 E 9 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		AG31 N 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG31 Q 6 {master.A_PlaySoundEx("weapons/sgpump","Auto");}
		//loop
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		
		TNT1 A 12 {master.A_PlaysoundEx("Ironsights", "Auto");}
		stop;
	}
}
class MarineASGReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 37;
	}
	States{
	Spawn:
		TNT1 A 4 NODELAY {master.A_PlaysoundEx("Ironsights", "Auto");}
		/*
		AG31 E 9 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		AG31 N 3 {master.A_PlaySoundEx("insertshell","Auto");}
		AG31 Q 6 {master.A_PlaySoundEx("weapons/sgpump","Auto");}
		*/
	LoadLoop:
		AG30 L 3;
		AG30 O 3 {master.A_PlaySoundEx("insertshell","Auto");}
		TNT1 A 0 A_JumpIfReloadCounter("LoadLoop")
		;
		TNT1 A 12 {master.A_PlaysoundEx("Ironsights", "Auto");}
		stop;
	}
}

class MarineASGReloadDrum : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 37;
	}
	States{
	Spawn:
		TNT1 A 13 NODELAY {master.A_PlaysoundEx("weapons/autoshotgun/drumreload1", "Auto");}
		TNT1 A 2 {master.A_PlaysoundEx("weapons/autoshotgun/drumreload2", "Auto");}
		TNT1 A 0 PB_SpawnCasing("EmptyASGDrum",28,0,30,3,Frandom(-8,-5),Frandom(1,4));
		//TNT1 A 0 {master.A_FireCustomMissile("EmptyASGDrum",-5,0,0,-4);}
		AU34 A 4 {master.A_PlaysoundEx("Ironsights", "Auto");}
		TNT1 A 7 {master.A_PlaySoundEx("weapons/sgmvpump","Auto");}
		AVMD LM 1 ;
		AVMD N 1 ;
		AU34 O 1 ;
		TNT1 A 7 {master.A_PlaysoundEx("weapons/shotgun/detach", "Auto");}
		TNT1 A 4 {master.A_PlaysoundEx("weapons/riflemagslap", "Auto");}
		AU35 A 4 ;
		TNT1 A 3 {master.A_PlaySoundEx("weapons/sgpump","Auto");}
		AU33 A 3;
		AU33 A 4;
		stop;
	}
}
class MarineASGReloadDrum2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 37;
	}
	States{
	Spawn:
		TNT1 A 13 NODELAY {master.A_PlaysoundEx("weapons/autoshotgun/drumreload1", "Auto");}
		TNT1 A 2 {master.A_PlaysoundEx("weapons/autoshotgun/drumreload2", "Auto");}
		AU34 A 13 {master.A_PlaysoundEx("Ironsights", "Auto");}
		AVMD LM 1 ;
		AVMD N 1 ;
		AU34 O 1 ;
		TNT1 A 7 {master.A_PlaysoundEx("weapons/shotgun/detach", "Auto");}
		TNT1 A 4 {master.A_PlaysoundEx("weapons/riflemagslap", "Auto");}
		AU35 A 4 ;
		TNT1 A 3 ;
		AU33 A 3;
		AU33 A 4;
		stop;
	}
}
class MarineDMRReload : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 75;
	}
	States{
	Spawn:
		TNT1 A 18;
		TNT1 A 4 {master.A_PlaySoundEx("weapons/rifle/magout", "Auto");}
		TNT1 E 1 {master.A_PlaySoundEx("weapons/rifle/magchange", "Auto");}
		TNT1 E 3 PB_SpawnCasing("EmptyDMRMag",38,26,7,frandom(0, 3.5),frandom(-7.2, -3.3),frandom(3,7));
		TNT1 E 4 {master.A_PlaySoundEx("Ironsights", "Auto");}
		TNT1 E 9 {master.A_PlaySoundEx("weapons/rifle/magin", "Auto");}
		TNT1 E 1 {master.A_PlaySoundEx("weapons/rifle/magslap", "Auto");}
		TNT1 E 13 {master.A_PlaySoundEx("weapons/rifle/magslap", "Auto");}
		TNT1 E 4 ;//{master.A_PlaySound("weapons/ssg/inspect3");}
		TNT1 E 18 {master.A_PlaySoundEx("RIFCL_CK", "auto");}
		stop;
	}
}
class MarineDMRReload2 : MarineReloadFX{
	Default{
		MarineReloadFX.MarineAttackCooldown 75;
	}
	States{
	Spawn:
		TNT1 A 18;
		TNT1 A 4 {master.A_PlaySoundEx("weapons/rifle/magout", "Auto");}
		TNT1 E 1 {master.A_PlaySoundEx("weapons/rifle/magchange", "Auto");}
		TNT1 E 3 ;//PB_SpawnCasing("EmptyDMRMag",38,26,7,frandom(0, 3.5),frandom(-7.2, -3.3),frandom(3,7));
		TNT1 E 4 {master.A_PlaySoundEx("Ironsights", "Auto");}
		TNT1 E 9 {master.A_PlaySoundEx("weapons/rifle/magin", "Auto");}
		TNT1 E 1 {master.A_PlaySoundEx("weapons/rifle/magslap", "Auto");}
		TNT1 E 13 {master.A_PlaySoundEx("weapons/rifle/magslap", "Auto");}
		TNT1 E 4 ;//{master.A_PlaySound("weapons/ssg/inspect3");}
		//TNT1 E 18 {master.A_PlaySoundEx("RIFCL_CK", "auto");}
		stop;
	}
}
class MarineCarbineReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 15;
		TNT1 A 0 {master.A_PlaySoundEx("weapons/carbine/magout", "Auto");}
		TNT1 E 11 PB_SpawnCasing("EmptyCarbineMag",38,20,13,frandom(0, 3.5),frandom(-7.2, -3.3),frandom(3,7));
		TNT1 E 10 {master.A_StartSound("weapons/carbine/magin", CHAN_AUTO);}
		TNT1 E 9 {master.A_StartSound("weapons/riflemagslap", CHAN_AUTO);}
		TNT1 E 4 ;
		TNT1 E 8 {master.A_StartSound("weapons/magpull", CHAN_AUTO);}
		TNT1 E 7 ;
		stop;
	}
}
class MarineCarbineReload2 : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 15;
		TNT1 A 0 {master.A_PlaySoundEx("weapons/carbine/magout", "Auto");}
		TNT1 E 11 PB_SpawnCasing("EmptyCarbineMag",38,20,13,frandom(0, 3.5),frandom(-7.2, -3.3),frandom(3,7));
		TNT1 E 10 {master.A_StartSound("weapons/carbine/magin", CHAN_AUTO);}
		TNT1 E 9 {master.A_StartSound("weapons/riflemagslap", CHAN_AUTO);}
		TNT1 E 7 ;
		stop;
	}
}
class MarineLMGReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 9;
		TNT1 A 10 {master.A_StartSound("LLIDOP");}
		LLBU A 19;
		TNT1 A 5 {master.A_StartSound("weapons/sgl/detach", 3);}
		TNT1 A 8 PB_SpawnCasing("EmptyLMGMag", 12, -2.5, 10.25,frandom(2,5),frandom(1,3),frandom(2,4));
		TNT1 A 10 {master.A_StartSound("weapons/lmg/magin", 4);}
		TNT1 A 18 {master.A_StartSound("weapons/riflemagslap", 5);}
		TNT1 A 16 {master.A_StartSound("LFEED");}
		TNT1 A 10 {master.A_StartSound("LLIDCL");}
		Rechamber:
		TNT1 A 6;
		TNT1 A 12 {master.A_StartSound("IronSights", 1);master.A_StartSound("LMGCLK", 2);}
		stop;
	}
}
class MarineLMGReload2 : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 9;
		TNT1 A 10 {master.A_StartSound("LLIDOP");}
		TNT1 S 3;
		TNT1 A 5 {master.A_StartSound("", 2);}
		TNT1 ABCD 1;
		TNT1 A 10 {master.A_StartSound("weapons/sgl/detach", 3);}
		TNT1 OP 1;
		TNT1 A 10 {master.A_StartSound("weapons/lmg/magin", 4);}
		TNT1 A 18 {master.A_StartSound("weapons/riflemagslap", 5);}
		TNT1 A 16 {master.A_StartSound("LFEED");}
		TNT1 A 10 {master.A_StartSound("LLIDCL");}
		stop;
	}
}
class MarineMG42BarrelChange : MarineReloadFX{
	States{
	Spawn:
		MGC1 A 15;
		TNT1 A 17 {master.A_PlaySound("MG42OP");}
		TNT1 A 10 {master.A_PlaySound("MG42RE");}
		TNT1 A 17 {master.A_PlaySound("MG42IN");}
		TNT1 A 10 {master.A_PlaySound("MG42CL");}
		TNT1 A 13 {master.A_PlaySound("MG42RC");}
		stop;
	}
}
class MarineNailgunReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 16 NODELAY {master.A_StartSound("8HAINAMO", CHAN_AUTO);}
		TNT1 A 14 {master.A_StartSound("weapons/nailgun/inspect4", CHAN_AUTO);}
		TNT1 A 15 {master.A_StartSound("weapons/nailgun/inspect8", CHAN_AUTO);}
		TNT1 A 4 {master.A_StartSound("weapons/nailgun/inspect3", CHAN_AUTO);}
		TNT1 A 34 {master.A_StartSound("weapons/nailgun/inspect6", CHAN_AUTO);}
		TNT1 A 6 {master.A_StartSound("weapons/nailgun/inspect4", CHAN_AUTO);}
		TNT1 A 9 {master.A_StartSound("weapons/nailgun/inspect7", CHAN_AUTO);}
		stop;
	}
}
class MarineRocketLauncherReload : MarineReloadFX{
	States{
	Spawn:
		RL19 A 6;
		TNT1 A 9 {master.A_StartSound("weapons/nailgun/inspect4", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 3 {master.A_StartSound("weapons/rocket/magpop", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 8 PB_SpawnCasing("EmptyRLMagazine", 25, 8, 25, frandom(4,8), 0, frandom(1,3));
		TNT1 A 18 {master.A_StartSound("weapons/rocket/magplace", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 8 {master.A_StartSound("weapons/sgl/slap", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 0 {master.A_StartSound("weapons/rocket/handling", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 6 {master.A_StartSound("weapons/rocket/innercycle", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 8 {master.A_StartSound("RLCYCLE2", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 6 {master.A_StartSound("weapons/rocket/loadingmechanism2", CHAN_AUTO, CHANF_OVERLAP);}
		stop;
	}
}
class MarineRocketLauncherReload2 : MarineReloadFX{
	States{
	Spawn:
		RL19 A 6;
		TNT1 A 9 {master.A_StartSound("weapons/nailgun/inspect4", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 11 {master.A_StartSound("weapons/rocket/magpop", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 18 {master.A_StartSound("weapons/rocket/magplace", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 8 {master.A_StartSound("weapons/sgl/slap", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 9 {master.A_StartSound("weapons/rocket/handling", CHAN_AUTO, CHANF_OVERLAP);}
		stop;
	}
}
class MarineGrenadeLauncherReload : MarineReloadFX{
	States{
	Spawn:
			TNT1 A 10 NODELAY {master.A_StartSound("Ironsights",15);}
			TNT1 A 1 {master.A_StartSound("weapons/sgl/detach", 14);}
			TNT1 A 12 {//if (CountInv("GrenadeRounds") == 0 )
			/*{
				if(A_GetCurrentGrenadeType() == "Sticky")
				{PB_SpawnCasing("SGL_StickyDrum",25,0,20,Frandom(3,4),Frandom(3,4),1);}
				else if(A_GetCurrentGrenadeType() == "Incendiary")
				{PB_SpawnCasing("SGL_IncendiaryDrum",25,0,20,Frandom(3,4),Frandom(3,4),1);}
				else if(A_GetCurrentGrenadeType() == "Cryo")
				{PB_SpawnCasing("SGL_CryoDrum",25,0,20,Frandom(3,4),Frandom(3,4),1);}
				else if(A_GetCurrentGrenadeType() == "Acid")
				{PB_SpawnCasing("SGL_AcidDrum",25,0,20,Frandom(3,4),Frandom(3,4),1);}
				else {
				PB_SpawnCasing("SGL_Drum",25,0,20,Frandom(3,4),Frandom(3,4),1);}
				}
				*/
				PB_SpawnCasing("SGL_Drum",25,0,20,Frandom(3,4),Frandom(3,4),1);
			}
			TNT1 A 6 {master.A_StartSound("weapons/nailgun/up", 10);}
			TNT1 A 13 {master.A_StartSound("weapons/sgl/inspect1", 16);}
			TNT1 A 10 {master.A_StartSound("weapons/nailgun/inspect4", 9, CHANF_OVERLAP );master.A_StartSound("RLCYCLE2", 13);}
			TNT1 A 4 {master.A_StartSound("weapons/sgl/cycle", 18);}
			TNT1 A 17 {master.A_StartSound("weapons/sgl/cycle", 12);}
			stop;
	}
}
class MarineGrenadeLauncherReload2 : MarineReloadFX{
	States{
	Spawn:
			TNT1 A 10 NODELAY {master.A_StartSound("Ironsights",15);}
			TNT1 A 13 {master.A_StartSound("weapons/sgl/detach", 14);}
			TNT1 A 6 {master.A_StartSound("weapons/nailgun/up", 10);}
			TNT1 A 13 {master.A_StartSound("weapons/sgl/inspect1", 16);}
			TNT1 A 1 {master.A_StartSound("weapons/sgl/slap", 9, CHANF_OVERLAP );}
			TNT1 A 5 {master.A_StartSound("weapons/nailgun/inspect4", 17, CHANF_OVERLAP );}
			TNT1 A 6 {master.A_StartSound("Ironsights", 12);}
			stop;
	}
}
class MarineM1PlasmaReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 25 NODELAY {master.A_PlaySoundEx("PLSM2RL", "Auto");}
		TNT1 A 6 {master.A_PlaySoundEx("weapons/plasma/cellout","Auto");}
		P1R0 K 14 PB_SpawnCasing("EmptyCell",29,random(10,12),20,0,random(-4,-2),2);
		TNT1 A 21 {master.A_PlaySoundEx("weapons/plasma/cellin","Auto");}
		stop;
	}
}
class MarineM2PlasmaReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 7 NODELAY {
			master.A_PlaySoundEx("Ironsights", "Auto");
			master.A_PlaySoundEx("PLSM2RL","Auto");
		}
		M220 H 4 {
			master.A_PlaySoundEx("weapons/m2plasma/screenup", "Auto");
			master.A_PlaysoundEx("Weapons/CellEject","Auto");
			}
		TNT1 A 18 PB_SpawnCasing("EmptyCell",38,22,38,Frandom(2,5),Frandom(10,15),Frandom(5,8));
		M220 A 15 {master.A_PlaySoundEx("weapons/m2plasma/reload", "Auto");}
		stop;
	}
}
class MarineM1PlasmaReload2 : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 25 NODELAY {master.A_PlaySoundEx("PLSM2RL", "Auto");}
		TNT1 A 6 {master.A_PlaySoundEx("weapons/plasma/cellout","Auto");}
		P1R0 K 14 ;//PB_SpawnCasing("EmptyCell",29,random(10,12),20,0,random(-4,-2),2);
		TNT1 A 21 {master.A_PlaySoundEx("weapons/plasma/cellin","Auto");}
		stop;
	}
}
class MarineM2PlasmaReload2 : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 7 NODELAY {
			master.A_PlaySoundEx("Ironsights", "Auto");
			master.A_PlaySoundEx("PLSM2RL","Auto");
		}
		M220 H 4 {
			master.A_PlaySoundEx("weapons/m2plasma/screenup", "Auto");
			master.A_PlaysoundEx("Weapons/CellEject","Auto");
			}
		TNT1 A 18 ;//PB_SpawnCasing("EmptyCell",38,22,38,Frandom(2,5),Frandom(10,15),Frandom(5,8));
		M220 A 15 {master.A_PlaySoundEx("weapons/m2plasma/reload", "Auto");}
		stop;
	}
}
class MarineRailgunReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 15 NODELAY {
			master.A_StopSound(1);
			master.A_StopSound(7);
			master.A_StopSound(6);
			master.A_StartSound("weapons/nailgun/up", CHAN_AUTO, CHANF_OVERLAP);
		}
		TNT1 A 7 {master.A_StartSound("weapons/CryoRifle/respect2", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 7 PB_SpawnCasing("EmptyCell", 28, 11, 20, 1, random(2,4), 4);
		TNT1 A 5 {master.A_StartSound("Ironsights", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 14 {master.A_StartSound("weapons/plasma/cellin", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 3 {master.A_StartSound("weapons/riflemagslap", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 6 {master.A_StartSound("weapons/carbine/fancybutton", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 9 {master.A_StartSound("weapons/nailgun/inspect1", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 23 {master.A_StartSound("weapons/railgun/inspect5", CHAN_AUTO, CHANF_OVERLAP);}
		stop;
	}
}
class MarineRailgunReload2 : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 15 NODELAY {
			master.A_StopSound(1);
			master.A_StopSound(7);
			master.A_StartSound("weapons/nailgun/up", CHAN_AUTO, CHANF_OVERLAP);
		}
		TNT1 A 14 {master.A_StartSound("weapons/CryoRifle/respect2", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 5 {master.A_StartSound("Ironsights", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 14 {master.A_StartSound("weapons/plasma/cellin", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 3 {master.A_StartSound("weapons/riflemagslap", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 6 {master.A_StartSound("weapons/carbine/fancybutton", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 9 {master.A_StartSound("weapons/nailgun/inspect1", CHAN_AUTO, CHANF_OVERLAP);}
		TNT1 A 23 {master.A_StartSound("weapons/railgun/inspect5", CHAN_AUTO, CHANF_OVERLAP);}
		stop;
	}
}
class MarineFlameThrowerReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 11 NODELAY {master.A_StartSound("IronSights", CHAN_AUTO);}
		TNT1 A 11 {
				master.A_StartSound("LIGHTON", CHAN_AUTO);
				master.A_StartSound("weapons/flamethrower/hiss2", CHAN_AUTO);
			}
		TNT1 A 4 {master.A_StartSound("weapons/flamethrower/respect6", CHAN_AUTO);}
		TNT1 A 7 {
				master.A_StartSound("weapons/flamethrower/lighthiss", CHAN_6);
				master.A_StartSound("weapons/flamethrower/respect4", CHAN_AUTO);
			}
		TNT1 A 11 {master.A_StartSound("weapons/flamethrower/respect3", CHAN_AUTO);}
		FRE1 R 3 {
			master.A_StartSound("weapons/flamethrower/misc1", CHAN_5);
			PB_SpawnCasing("FlamerEmptyPB_Fuel", 30, 6, 11,frandom(-2,2),frandom(-4,-2),frandom(3,5));
		}
		TNT1 A 0 {master.A_StartSound("weapons/flamethrower/hiss1", CHAN_6);}
		FRE1 UVWXYZ 1 {master.A_SpawnItemEx("GunFireSmoke", 8, 16, 35, 4, -6, 2, -2, SXF_NOCHECKPOSITION );}
		FRE2 A 10;
		TNT1 A 6 {master.A_StartSound("weapons/flamethrower/respect3", CHAN_AUTO);}
		TNT1 A 10 {master.A_StartSound("weapons/flamethrower/respect4", CHAN_AUTO);}
		TNT1 A 13 {master.A_StartSound("weapons/flamethrower/respect4", CHAN_AUTO);}
		TNT1 A 19 {master.A_StartSound("weapons/flamethrower/respect2", CHAN_AUTO);}
		TNT1 A 0 {
			master.A_StartSound("weapons/flamethrower/respect3", CHAN_AUTO);
			master.A_StartSound("weapons/flamethrower/hiss2", CHAN_AUTO);
		}
		FRE4 GHIJKLMNOPQRSTUVWXY 1 {master.A_SpawnItemEx("GunFireSmoke", 8, 0, 38, 2, -5, 7, 2, SXF_NOCHECKPOSITION);}
		stop;
	}
}
class MarineFlameThrowerReload2 : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 11 NODELAY {master.A_StartSound("IronSights", CHAN_AUTO);}
		TNT1 A 11 {
				master.A_StartSound("LIGHTON", CHAN_AUTO);
				master.A_StartSound("weapons/flamethrower/hiss2", CHAN_AUTO);
			}
		TNT1 A 4 {master.A_StartSound("weapons/flamethrower/respect6", CHAN_AUTO);}
		TNT1 A 7 {
				master.A_StartSound("weapons/flamethrower/lighthiss", CHAN_6);
				master.A_StartSound("weapons/flamethrower/respect4", CHAN_AUTO);
			}
		TNT1 A 11 {master.A_StartSound("weapons/flamethrower/respect3", CHAN_AUTO);}
		FRE1 R 3 {
			master.A_StartSound("weapons/flamethrower/misc1", CHAN_5);
		}
		TNT1 A 0 {master.A_StartSound("weapons/flamethrower/hiss1", CHAN_6);}
		FRE1 UVWXYZ 1 {master.A_SpawnItemEx("GunFireSmoke", 8, 16, 35, 4, -6, 2, -2, SXF_NOCHECKPOSITION );}
		FRE2 A 10;
		TNT1 A 6 {master.A_StartSound("weapons/flamethrower/respect3", CHAN_AUTO);}
		TNT1 A 10 {master.A_StartSound("weapons/flamethrower/respect4", CHAN_AUTO);}
		TNT1 A 13 {master.A_StartSound("weapons/flamethrower/respect4", CHAN_AUTO);}
		TNT1 A 19 {master.A_StartSound("weapons/flamethrower/respect2", CHAN_AUTO);}
		TNT1 A 0 {
			master.A_StartSound("weapons/flamethrower/respect3", CHAN_AUTO);
			master.A_StartSound("weapons/flamethrower/hiss2", CHAN_AUTO);
		}
		FRE4 GHIJKLMNOPQRSTUVWXY 1 {master.A_SpawnItemEx("GunFireSmoke", 8, 0, 38, 2, -5, 7, 2, SXF_NOCHECKPOSITION);}
		stop;
	}
}
class MarineDemonTechReload : MarineReloadFX{
	States{
	Spawn:
		TNT1 A 11 A_PlaySoundEx("Ironsights", "Auto");
		TNT1 A 3 A_PlaySoundEx("weapons/riflemagslap", "Auto");
		TNT1 A 20 A_PlaySoundEx("weapons/demontech/respect1", "Auto");
		TNT1 A 5 A_PlaySound("weapons/fistwhoosh2");
		TNT1 A 1 A_PlaySoundEx("weapons/demontech/respect4", "Auto");
		TNT1 A 0 A_PlaySoundEx("weapons/demontech/respect2", "Auto");
		TNT1 A 32 A_PlaySoundEx("HRPickup", "Auto");
		TNT1 A 14 A_PlaySoundEx("Ironsights", "Auto");
		TNT1 A 14 A_PlaySoundEx("weapons/demontech/respect3", "Auto");
		TNT1 A 4 A_PlaySoundEx("weapons/riflemagslap", "Auto");
		TNT1 A 20 A_PlaySoundEx("HRSteam", "Auto");
		stop;
	}
}