class MarineGrenadeExplosion : PBMarineProjectile{
Default{
	+NOBLOCKMAP
	+MISSILE
	Damagetype "ExplosiveImpact";
	DeathSound "Explosion";
}
States{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("WhiteShockwave");
		TNT1 A 0 A_SpawnItemEx("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAA 0 A_CustomMissile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 A_CustomMissile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAA 0 A_CustomMissile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream;
		TNT1 A 0 A_ALertMonsters;
		TNT1 AAA 0 A_CustomMissile("ShrapnelParticle2", 0, 0, random(0, 360), 2, random(5, 90));
		TNT1 A 0 A_Playsound("excavator/explode", 1);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		TNT1 AAA 8 A_CustomMissile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(50, 130));
		Stop;
	}
}

Class PBMarine_ACIDFOG : PBMarineProjectile{
	Default{
	Radius 2;
	Height 1;
	Decal "Scorch";
	Damage 1;
	DamageType "Disintegrate";
	Scale 1.32;
	Speed 0;
	Gravity 0;
	+NOBLOCKMAP
	+NOTELEPORT
	+NOEXTREMEDEATH
	-EXTREMEDEATH
	+FORCEXYBILLBOARD
	+ALLOWPARTICLES
	+CLIENTSIDEONLY
	+DONTSPLASH
	+PAINLESS
	-CAUSEPAIN
	-FORCEPAIN
	}
	States{
			Spawn:
			TNT1 A 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 0, 6, 6, 6, 0, 128);
			TNT1 A 0 A_Explode( 100, 120, 0, 0, 90 );
			TNT1 AAAAAA 0 A_SpawnItemEx("PBMarine_GreenCloudLarge", random(3,-3), random(3,-3), random(3,-3), random(1,-1), random(1,-1), 0, 0, SXF_NOCHECKPOSITION, 0);
			TNT1 AAAAAA 0 A_SpawnItemEx("PBMarine_GreenCloudMedium", random(3,-3), random(3,-3), random(3,-3), random(1,-1), random(1,-1), 0, 0, SXF_NOCHECKPOSITION, 0);
			TNT1 AAAAAA 0 A_SpawnItemEx("PBMarine_GreenCloudSmall", random(3,-3), random(3,-3), random(3,-3), random(1,-1), random(1,-1), 0, 0, SXF_NOCHECKPOSITION, 0);
			TNT1 AAAAA 0 A_SpawnItemEx("GreenTrailSparks", random(10,-10), random(10,-10), random(10,-10), random(-2, 2), random(-2, 2), random(-2, 2), 0, SXF_NOCHECKPOSITION, 0);
			TNT1 A 0 A_SpawnItemEx("NewAcidExplosionSmoke", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION, 0);
			TNT1 AAAA 2 BRIGHT Light("BARONBALL") A_SpawnItem("GreenFlare",0,20);
			Goto Death;
		Death:
			TNT1 A 60;
			Stop;
	}
}
Class PBMarine_GreenCloudSmall : PBMarineProjectile{
Default{
	PROJECTILE;
	-ACTIVATEIMPACT
	-ACTIVATEPCROSS
	+NODAMAGETHRUST
	+ADDITIVEPOISONDAMAGE
	+BLOODLESSIMPACT
	+NOTELEPORT
	+RIPPER
	+NOBLOOD
	+NOEXTREMEDEATH
	-EXTREMEDEATH
	+FORCEXYBILLBOARD
	-ALLOWPARTICLES
	+DONTSPLASH
	+PAINLESS
	-CAUSEPAIN
	-FORCEPAIN
	-SOLID
	Radius 0;
	Height 0;
	Scale 0.85;
	PoisonDamage 1;
	DamageType "Disintegrate";
	PoisonDamageType "Disintegrate";
	Speed 1;
	Alpha 0.55;
	RenderStyle "add";
	Seesound "redburn";
	}
	States{
	Spawn:
		GTXL KLMNOPQRST 1 
		{
			if(CountInv("Timer555") < 1)
			{
				A_FadeIn(0.10);
			}
		}
		TNT1 A 0 A_GiveInventory("Timer555",1);
		TNT1 A 0 A_Explode( 7, 100, 0, 40);
		GTXL TSRQPONMLK 1 ;
		TNT1 A 0 A_Explode( 7, 100, 0, 40 );
		TNT1 A 0 A_JumpIfInventory("Timer555",5,1);
		Loop;
		TNT1 AA 0;
		GTXL KLMNOPQRST 1  A_FadeOut( 0.10);
		Stop;
	}
}

Class PBMarine_GreenCloudMedium : PBMarine_GreenCloudSmall{
	Default{
	Scale 1.3;
	DamageType "Disintegrate";
	}
	States{
	Spawn:
		GTXL KLMNOPQRST 1 
		{
			if(CountInv("Timer555") < 1)
			{
				A_FadeIn(0.10);
			}
		}
		TNT1 A 0 A_GiveInventory("Timer555",1);
		TNT1 A 0 A_Explode( 9, 100, 0, 60);
		GTXL TSRQPONMLK 1 ;
		TNT1 A 0 A_Explode( 9, 100, 0, 60);
		TNT1 A 0 A_JumpIfInventory("Timer555",5,1);
		Loop;
		TNT1 AA 0;
		GTXL KLMNOPQRST 1  A_FadeOut( 0.10);
		Stop;
	}
}

Class PBMarine_GreenCloudLarge : PBMarine_GreenCloudSmall{
	Default{
	Scale 1.55;
	DamageType "Disintegrate";
	SeeSound "world/barrelloop";
	}
	States{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("world/barrelloop", 4, 1, 1);
	SpawnLoop:
		GTXL KLMNOPQRST 1 
		{
			if(CountInv("Timer555") < 1)
			{
				A_FadeIn(0.10);
			}
		}
		TNT1 A 0 A_GiveInventory("Timer555",1);
		TNT1 AA 0 A_SpawnItemEx("GreenTrailSparks", random(10,-10), random(10,-10), random(10,-10), random(-2, 2), random(-2, 2), random(-2, 2), 0, SXF_NOCHECKPOSITION, 0);
		TNT1 A 0 A_Explode( 12, 100, 0, 80);
		GTXL TSRQPONMLK 1 ;
		TNT1 AA 0 A_SpawnItemEx("GreenTrailSparks", random(10,-10), random(10,-10), random(10,-10), random(-2, 2), random(-2, 2), random(-2, 2), 0, SXF_NOCHECKPOSITION, 0);
		TNT1 A 0 A_Explode( 12, 100, 0, 80);
		TNT1 A 0 A_JumpIfInventory("Timer555",5,1);
		Loop;
		TNT1 AA 0;
		TNT1 A 0 A_StopSound(4);
		GTXL KLMNOPQRST 1  A_FadeOut( 0.10);
		Stop;
	}
}
