Class PBMarine_FragGrenade : PBMarineProjectile {
	Default{
	Radius 2;
	Height 2;
	speed 44;
	Damage 30;
	DamageType "Explosive";
	Species "Marines";
	+MISSILE
	+BLOODSPLATTER
	+EXTREMEDEATH
	+FORCEXYBILLBOARD
	+CANBOUNCEWATER
	+DONTBOUNCEONSHOOTABLES
	+USEBOUNCESTATE
	+BOUNCEONWALLS
	+BOUNCEONFLOORS
	+BOUNCEONCEILINGS
	+THRUSPECIES
	+MTHRUSPECIES
	+DONTHARMSPECIES
	Bouncetype "Doom";
	BounceFactor 0.5;
	Scale .35;
	Gravity 1.0;
	Decal "Scorch";
	SeeSound "weapon/grenade";
	BounceSound "weapon/grenade";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
	}
	
	States{
		Spawn:
			TNT1 A 0 {
				if(waterlevel > 1) {A_SpawnItem("RocketSmokeTrail52"); }
				A_SpawnItem("YellowFlareSmall",0,0);
			}
			GRNP A 1 Bright Light("SGL_FRAG") ;
			Loop;
		Bounce:
			TNT1 A 0;
			TNT1 A 0 {
			if(GetCvar("pb_sglgrenadeimpact") == 1)
			{ return ResolveState("Death");}
			else if(GetCvar("pb_sglgrenadeimpact") >=2)
			{
				A_Stop();
				return ResolveState("Rest");
			 }
			return ResolveState(null);
			}
			Goto spawn;
		Rest:
		GRNP A 35 Bright Light("SGL_FRAG") A_JumpIfInventory("GrenadeDetonator",1,"Detonate",AAPTR_TARGET);
		Detonate:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("Explosion");
		Death:
		XDeath:
			TNT1 A 0 A_SpawnItemEx("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			//TNT1 A 0 A_SpawnItemEx("ImpactGrenadeExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 0, 0, 0);
			TNT1 A 1;
			XXXX A 0 A_CustomMissile("ExplosionQuake", 1, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAAAAAAA 0 A_CustomMissile("MediumExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL",3);
			EXPL AAA 0 A_CustomMissile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
			TNT1 A 1;
			TNT1 A 0 A_Explode(200,200,0);
			Stop;
	}
}
Class PBMarine_IncendiaryGrenade : PBMarine_FragGrenade
{
	Default{
	DamageType "Fire";
	Decal "BigScorch";
	SeeSound "weapon/grenade";
	DeathSound "weapons/sgl/incendiary";
	}
	States
	{
		Spawn:
			TNT1 A 0 {
				if(waterlevel > 1) {A_SpawnItem("BurningEmberParticlesFloating_Bigger"); }
				A_SpawnItem("OrangeFlareSmall",0,0);
			}
			GRNP A 1 Bright Light("SGL_INCENDIARY") ;
			Loop;
			
		Bounce:
			TNT1 A 0;
			TNT1 A 0 {
			if(GetCvar("pb_sglgrenadeimpact") == 1)
			{ return ResolveState("Death");}
			else if(GetCvar("pb_sglgrenadeimpact") >=2)
			{
				A_Stop();
				return ResolveState("Rest");
			 }
			return ResolveState(null);
			}
			Goto spawn;
		
		Rest:
		GRNP A 35 Bright Light("SGL_INCENDIARY") ;
		Detonate:
			TNT1 A 0;
			TNT1 A 0 A_Playsound("weapons/sgl/incendiary");
		Death:
		XDeath:
			TNT1 A 0 A_Explode(100, 100);
			TNT1 A 0 A_ChangeFlag("NOGRAVITY", 0);
			EXPL A 0 A_SpawnItem("ExplosionParticleSpawner");
			TNT1 A 0 A_SpawnItemEx("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("IncendiaryGrenadeFX", 0, 0, 0);
			TNT1 AAAA 0 A_CustomMissile("FireworkSFXType2", 64, 0, random(0, 360), 2, random(30, 60));
			EXPL AAAAAAAAAA 0 A_CustomMissile("FireballExplosionFlamesBig", 6, 0, random(0, 360), 2, random(0, 360));
			FRFX ZZZ 0 BRIGHT A_CustomMissile("BigNeoSmoke", 2, 0, random(0, 360), 2, random(0, 360));
			EXPL AAAAA 0 A_CustomMissile("PBMarine_FT_GroundFireSpawner", 12, random(-32,32), random(0, 360), 2, random(40, 60));
			EXPL AAAAAAAAAA 0 A_CustomMissile("PBMarine_FT_GroundFireSpawner", random(-32,32), 0, random(0, 360), 2, random(50, 130));
			Stop;
	}
}

Class PBMarine_CryoGrenade: PBMarine_FragGrenade{
	Default{
		DamageType "Freeze";
		DeathSound "weapons/CryoRifle/missiledeath";
		Decal "FreezerBurn";
		+NODAMAGETHRUST
		+FORCEXYBILLBOARD
		+FORCERADIUSDMG
		+BLOODLESSIMPACT
	}
	States{
		Spawn:
			TNT1 A 0 {
				if(waterlevel > 1) {A_SpawnItem("CryoRifleTrailSparksSmall"); }
				A_SpawnItem("BlueFlareSmall",0,0);
			}
			GRNP A 1 Bright Light("SGL_CRYO") ;
			Loop;
			
		Bounce:
			TNT1 A 0;
			TNT1 A 0 {
			if(GetCvar("pb_sglgrenadeimpact") == 1)
			{ return ResolveState("Death");}
			else if(GetCvar("pb_sglgrenadeimpact") >=2)
			{
				A_Stop();
				return ResolveState("Rest");
			 }
			return ResolveState(null);
			}
			Goto spawn;
		
		Rest:
		GRNP A 35 Bright Light("SGL_CRYO") ;
		Detonate:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
		Death:
		XDeath:
			TNT1 A 0 Bright A_StopSound(CHAN_BODY);
			TNT1 A 0 Bright A_ChangeFlag("ICEDAMAGE", 1);
			TNT1 A 0 Bright A_ChangeFlag("NODAMAGETHRUST", 0) ;
			TNT1 A 0 Bright A_Explode(200,120, 0, 0, 120);
			TNT1 AAA 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
			TNT1 AAA 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
			TNT1 AAA 0 Bright A_SpawnItemEx("CryoRifleTrailSparksSmall", random(5,-5), random(5,-5), random(5,-5), random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
			TNT1 AAA 0 Bright A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
			TNT1 AAA 0 Bright A_SpawnItemEx("IceExplosionImpact", random(-2,2), random(-2,2), random(-2,2), 0, 0, 0, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
			TNT1 AAAAA 0 A_SpawnItemEx("DetectFloorIce",random(-150,150), random(-150,150),1,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("DetectFloorCraterIce",0,0,1,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
	}
}

Class PBMarine_AcidGrenade : PBMarine_FragGrenade{
	Default{
	Damage 15;
	DamageType "Disintegrate";
	Decal "Scorch";
	DeathSound "Daedabus/impact";
	Obituary "$OB_MPROCKET";
	}
	States{
		Spawn:
			TNT1 A 0 {
				if(waterlevel > 1) {A_SpawnItem("GreenTrailSparks"); }
				A_SpawnItem("GreenFlareSmall",0,0);
			}
			GRNP A 1 Bright Light("SGL_ACID") A_JumpIfInventory("GrenadeDetonator",1,"Detonate",AAPTR_TARGET);
			Loop;
		
		Bounce:
			TNT1 A 0;
			TNT1 A 0 {
			if(GetCvar("pb_sglgrenadeimpact") == 1)
			{ return ResolveState("Death");}
			else if(GetCvar("pb_sglgrenadeimpact") >=2)
			{
				A_Stop();
				return ResolveState("Rest");
			 }
			return ResolveState(null);
			}
			Goto spawn;
		
		Rest:
		GRNP A 35 Bright Light("SGL_ACID") ;
		Detonate:
			TNT1 A 0;
			TNT1 A 0 A_Playsound("Daedabus/impact");
		Death:
		XDeath:
			TNT1 A 0 A_SpawnItem("BFGAltShockWave",0,0);
			TNT1 A 0 A_SpawnItem("PBMarine_ACIDFOG", 0, 0);
			Stop;
	}
	
}

Class PBMarine_Rocket : PBMarineProjectile {
	Default{
		Radius 6;
		Height 6;
		Projectile;
		Speed 45;
		Damage 60;
		DamageType "Explosive";
		MeleeDamage 0;
		Gravity 0.00;
		Scale 0.48;
		Decal "Scorch";
		-NOGRAVITY
		+EXTREMEDEATH
		+BLOODSPLATTER 
		+THRUSPECIES
		+MTHRUSPECIES
		+RANDOMIZE
		SeeSound "weapons/RLL";
		DeathSound "Explosion";
		Species "Marine";
		Obituary "$OB_MPROCKET";
	}
	States{
		Spawn:
			MISL A 1 ;//Dummy Missile sprite for spawning, and so the Fly state doesn't mess up animation wise. -JMartinez2098 
			MISL A 1 A_StartSound("weapons/rocketloop",CHAN_BODY,CHANF_LOOP);
		Fly:
			M1SL ABCD 1 Bright Light("ROCKET") {
				if(waterlevel < 1) {
					A_SpawnItemEx("OldschoolRocketSmokeTrail2",-3,0,0,-1,0,0);
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
			Loop;
		Death:
			TNT1 A 2 {
				A_SpawnItem("WhiteShockwave");
				A_StopSound(CHAN_BODY);
				A_StartSound("FAREXPL", CHAN_AUTO|CHANF_OVERLAP);
				Radius_Quake(3, 8, 0, 15, 0);
				A_SpawnItemEx("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("NewRocketExploFX", 0, 0, 0);
				A_SpawnItemEx("LiquidExplosionEffectSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_CustomMissile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
				A_CustomMissile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
				A_CustomMissile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
				A_CustomMissile("MediumExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
				A_CustomMissile("MediumExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
				A_CustomMissile("MediumExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
				A_CustomMissile("PBExplosionparticles", 0, 0, random(0, 360), 2, random(40, 90));
				A_CustomMissile("PBExplosionparticles", 0, 0, random(0, 360), 2, random(40, 90));
				A_CustomMissile("PBExplosionparticles2", 0, 0, random(0, 360), 2, random(40, 90));
				A_CustomMissile("PBExplosionparticles2", 0, 0, random(0, 360), 2, random(40, 90));
				A_CustomMissile("PBExplosionparticles3", 10, 0, random(0, 360), 2, random(40, 90));
			}
			TNT1 A 23 A_Explode(200,150,0);
			Stop;
	}
}
Class PBMarine_HomingRocket_1 : PBMarine_Rocket{
	Default{
	+DEHEXPLOSION;
	+SKYEXPLODE;
	Speed 20;
	WeaveIndexXY 0;
	WeaveIndexZ 0;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			M1SL ABCDABCDABCD 1 Bright Light("ROCKET") {
				A_Weave(2, 2, random(-1,1), 2); // Full Weave
			}	
			TNT1 A 0 A_StartSound("weapons/rocket/rocketignite", CHAN_AUTO, CHANF_OVERLAP);
			MISL A 1 Bright Light("ROCKET") {
				A_StartSound("weapons/rocketloop",CHAN_BODY,CHANF_LOOP);
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_CustomMissile("PBExplosionparticles", 0, 0, random(0, 360), 2, random(40, 90));
				ACS_NamedExecuteAlways("homingRocketFollow_1",0,0,0,0);
			}
		Fly:
			M1SL ABCD 1 Bright Light("ROCKET") {
				A_Weave(0, 3, 0, 1); // Vertical Weave
				if(waterlevel < 1) {
					A_SpawnItemEx("OldschoolRocketSmokeTrail2",-3,0,0,-1,0,0);
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 Thing_Remove(30001);
			TNT1 A 0 ACS_NamedExecuteAlways("rocketCleanup",0,0,0,0);
			Goto Super::Death;
	}
}

Class PBMarine_HomingRocket_2 : PBMarine_HomingRocket_1{
	Default{
		WeaveIndexXY 1;
		WeaveIndexZ 0;
	}
	States {
		Spawn:
			TNT1 A 0;
			M1SL ABCDABCDABCD 1 Bright Light("ROCKET") {
				A_Weave(2, 2, random(-1,1), 2); // Full Weave
			}	
			TNT1 A 0 A_StartSound("weapons/rocket/rocketignite", CHAN_AUTO, CHANF_OVERLAP);
			MISL A 1 Bright Light("ROCKET") {
				A_StartSound("weapons/rocketloop",CHAN_BODY,CHANF_LOOP);
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_CustomMissile("PBExplosionparticles", 0, 0, random(0, 360), 2, random(40, 90));
				ACS_NamedExecuteAlways("homingRocketFollow_2",0,0,0,0);
			}
		Fly:
			M1SL ABCD 1 Bright Light("ROCKET") {
				A_Weave(3, 0, 1, 0); // Horizontal Weave
				if(waterlevel < 1) {
					A_SpawnItemEx("OldschoolRocketSmokeTrail2",-3,0,0,-1,0,0);
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 Thing_Remove(30002);
			TNT1 A 0 ACS_NamedExecuteAlways("rocketCleanup",0,0,0,0);
			Goto Super::Death;
	}
}

Class PBMarine_HomingRocket_3 : PBMarine_HomingRocket_1{
	Default{
	WeaveIndexXY 0;
	WeaveIndexZ 1;
	}
	States{
		Spawn:
			TNT1 A 0;
			M1SL ABCDABCDABCD 1 Bright Light("ROCKET") {
				A_Weave(2, 2, random(-1,1), 2); // Full Weave
			}	
			TNT1 A 0 A_StartSound("weapons/rocket/rocketignite", CHAN_AUTO, CHANF_OVERLAP);
			MISL A 1 Bright Light("ROCKET") {
				A_StartSound("weapons/rocketloop",CHAN_BODY,CHANF_LOOP);
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_CustomMissile("PBExplosionparticles", 0, 0, random(0, 360), 2, random(40, 90));
				ACS_NamedExecuteAlways("homingRocketFollow_3",0,0,0,0);
			}
		Fly:
			M1SL ABCD 1 Bright Light("ROCKET") {
				A_Weave(3, 3, -1, -1); // Full Weave
				if(waterlevel < 1) {
					A_SpawnItemEx("OldschoolRocketSmokeTrail2",-3,0,0,-1,0,0);
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 Thing_Remove(30003);
			TNT1 A 0 ACS_NamedExecuteAlways("rocketCleanup",0,0,0,0);
			Goto Super::Death;
	}
}
/*
Class MarineThrownGrenade : PBMarineProjectile{
	Default{
	Radius 2;
	Height 3;
	Speed 30;
	Damage 0;
	Gravity 0.7;
	Scale 0.2;
	Projectile;
	+MISSILE
	-NOPAIN
	-NOGRAVITY
	-BLOODSPLATTER
	-NOTELEPORT
	//-EXTREMEDEATH
	+EXPLODEONWATER
	+SKYEXPLODE
	+DOOMBOUNCE
	+FLOORCLIP
	+DONTGIB
	+SHOOTABLE
	+NOBLOOD
	-NOBLOCKMAP
	+MTHRUSPECIES
	+THRUSPECIES
	+DONTHURTSPECIES
	+DontHarmSpecies
	+UseBounceState
	+FORCEXYBILLBOARD
	DamageType "ExplosiveImpact";
	BounceFactor 0.5;
	WallBounceFactor 0.25;
	Health 5;
	SeeSound "GBOUNCE";
	DeathSound "none";
	Obituary "%o ate %k grenade.";
	}
	States
	{
	Spawn:
		TNT1 A 0 {
			if(GetCvar("pb_grenadeimpact") < 1)
			{
			 bUSEBOUNCESTATE == FALSE;
			 }
		}
		GRND ABCD 2;
		TNT1 A 0 A_GiveInventory("GrenadeTime",1);
		GRND EFGA 2;
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_Explode(1,500,XF_EXPLICITDAMAGETYPE,1,500,0,0,null,"Avoid");
		TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
		Loop;
	
	Bounce:
	Bounce.Floor:
	Bounce.Ceiling:
	Bounce.Wall:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
		TNT1 A 0 {
			if(GetCvar("pb_grenadeimpact") == 1)
			{ 
				//return ResolveState("Explode");
				SetState(FindState("Explode"));
			}
			else if(GetCvar("pb_grenadeimpact") >=2)
			{
				A_Stop();
				//return ResolveState("Death");
				SetState(FindState("Death"));
			 }
			//return ResolveState(null);
			//SetState(FindState("Death"));
		}
		Goto Spawn;

	Death.Kick:
	Death.ExtremePunches:
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 ;//A_Pain
		TNT1 A 0 A_Jumpif(GetCvar("pb_grenadeimpact") == 1, "Explode");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_CustomMissile("ThrownGrenade1", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;

	Death:
	XDEATH:
		TNT1 A 0;
		TNT1 A 0 A_Jumpif(GetCvar("pb_grenadeimpact") == 1, "Explode");
		GRND G 17;
		TNT1 A 0 A_GiveInventory("GrenadeTime",1);
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
		Loop;
	
	Death.ExplosiveImpact:
	Explode:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_StopSound(6);
		//TNT1 A 0 A_SpawnItem("FragGrenadeExplosion")
		TNT1 A 0;
		TNT1 A 0 ;
		TNT1 A 0 A_Explode(120,150, XF_HURTSOURCE);
		TNT1 A 0 A_SpawnItemEx("MarineGrenadeExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("WhiteShockwave");
		TNT1 A 0 A_CustomMissile("SparkSpawner",0,0,frandom(0,359),2,-15);
		TNT1 A 0 A_SpawnItemEx("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAA 0 A_CustomMissile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 A_CustomMissile("UnModHitSpark", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAA 0 A_CustomMissile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAA 0 A_CustomMissile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		TNT1 AAA 0 A_CustomMissile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
		TNT1 AAA 0 A_CustomMissile("HitSpark22", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
		TNT1 AAA 0 A_CustomMissile("HitSpark23", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
		BEXP B 0 BRIGHT A_Scream;
		TNT1 A 0 A_ALertMonsters;
		TNT1 AAA 0 A_CustomMissile("ShrapnelParticle2", 0, 0, random(0, 360), 2, random(5, 90));
		TNT1 A 0 A_Playsound("handgrenade/Explosion");
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		TNT1 A 0 A_SpawnItem("FragGrenadeExplosionSmoke");
		Stop;
	}
}
*/
class MarineThrownGrenade : PBMarineProjectile
{
	const FUSE_LENGTH = 70.0;
	
	int grenadeTicks;
	int nextBeepTime;
	bool wentKaput;
	Actor flareActor;

	int pbGrenadeDamage;
	int pbGrenadeRange;
	Property GrenadeExplosionParams : pbGrenadeDamage, pbGrenadeRange;

	string flareActorName;
	Property FlareActorName : flareActorName;

	Default {
		Radius 2;
		Height 3;
		Projectile;
		Speed 30;
		Damage 0;
		Gravity 0.7;
		Scale 0.2;
		+MISSILE;
		-NOGRAVITY;
		-BLOODSPLATTER;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		BounceType 'Doom';
		+FLOORCLIP;
		+DONTGIB;
		-NOBLOCKMAP;
		Species "Marines";
		+MTHRUSPECIES;
		+THRUSPECIES;
		+DontHarmSpecies;
		+UseBounceState;
		+RollSprite;
		+RollCenter;
		DamageType "ExplosiveImpact";
		BounceFactor 0.5;
		WallBounceFactor 0.25;
		BounceSound "GBOUNCE";
		DeathSound "none";
		Obituary "%o gobbled %k's grenade.";
		+FORCEXYBILLBOARD;

		MarineThrownGrenade.GrenadeExplosionParams 120, 150;
		MarineThrownGrenade.FlareActorName 'PB_GrenadeWarningFlare_Green';
	}

	override void Tick()
	{
		Super.Tick();

		if(wentKaput || IsFrozen())
			return;
		
		if(flareActor)
			flareActor.SetOrigin(self.pos, true);

		GrenadeTicks++;
			
		if(grenadeTicks >= nextBeepTime)
		{
			A_StartSound("grenade/beep", CHAN_AUTO);
			//A_SpawnItemEx("RedFlareSpawn");
			
			double delay = max(0.1 + 0.9 *((FUSE_LENGTH - grenadeTicks) / FUSE_LENGTH), 0.15);
			nextBeepTime = grenadeTicks + delay * 15;
			// console.printf("%i %i %i %f", grenadeTicks, nextBeepTime, grenadeTime, delay);
			
			if(flareActor)
				flareActor.alpha = flareActor.default.alpha;
		}
		else if(flareActor)
			flareActor.alpha *= 0.7;

		if(grenadeTicks >= FUSE_LENGTH)
			SetStateLabel("Explode");
	}
	
	override int SpecialBounceHit(Actor bounceMobj, Line bounceLine, SecPlane bouncePlane)
	{
		if(bouncePlane)
			roll = 0;
		else if(bounceLine)
			roll = 90;
			
		roll += frandom(-4.2, 4.2);
		
		if(pb_grenadeimpact && target && target.Player)
			SetStateLabel("Explode");
			
		return Super.SpecialBounceHit(bounceMobj, bounceLine, bouncePlane);
	}

	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		flareActor = Spawn(flareActorName, self.pos);
		nextBeepTime = 1;
	}
	
	States
	{
		Spawn:
			GRND G 1 NoDelay A_SetRoll(roll += 15, SPF_INTERPOLATE);
			Loop;
		Death:
			GRND G 1 { 
				A_SetRoll(0);
				A_Explode(1, 128, XF_EXPLICITDAMAGETYPE, true, 128, 0, 0, NULL, 'Avoid');
			}
		DeathLoop:
			GRND G 1;
			Loop;
		Explode:
			TNT1 A 0 
			{
				wentKaput = true;
				
				if(flareActor)
					flareActor.Destroy();
					
				A_SetRoll(0);
				A_Stop();
				A_StopSound(6);			

				if(target && target.Player)
					A_Explode(pbGrenadeDamage, pbGrenadeRange, XF_CIRCULAR);//A_SpawnItemEx("HandGrenadeExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
				else
					A_Explode(pbGrenadeDamage, pbGrenadeRange, XF_HURTSOURCE | XF_CIRCULAR);

				A_SpawnItemEx("WhiteShockwave");
				A_SpawnItem("WhiteShockwave");
				A_SpawnProjectile("SparkSpawner",0,0,frandom(0,359),2,-15);
				A_SpawnItemEx("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_StartSound("handgrenade/Explosion");
				A_StartSound("FAREXPL", 3);
					
				if(pos.z == floorz)
					A_SpawnItemEx("BarrelExplosionSmokeColumn");

				A_SpawnItemEx("FragGrenadeExplosionSmoke");
				A_AlertMonsters();
				A_Scream();
				Radius_Quake(2, 24, 0, 15, 0);
				
				if(pb_grenadeshrapnel)
				{
					for(int i = 0; i < 20; i++)
					{
						A_SpawnProjectile("PB_MarineShrapnel", 0, 0, random(0, 360), 2, random(-90, 90));
					}
				}
			}
			TNT1 AAA 0
			{ 
				A_SpawnProjectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnProjectile("UnModHitSpark", 0, 0, random(0, 360), 2, random(0, 180));
				SpawnExplosionParticleHeavySpark();
				SpawnExplosionParticleHeavySpark();
				SpawnExplosionParticleHeavySpark();
				SpawnExplosionParticleHeavySpark();
				A_SpawnProjectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
				A_SpawnProjectile("HitSpark22", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
				A_SpawnProjectile("HitSpark23", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
				SpawnShrapnerParticleSpark();
				SpawnShrapnerParticleSpark();
				SpawnShrapnerParticleSpark();
			}
			TNT1 A 2 {invoker.bFORCERADIUSDMG = true;}
			TNT1 A 0 {
				//A_Explode(180,220);
				if(target && target.Player)
					A_Explode(180,220);//A_SpawnItemEx("HandGrenadeExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
				else
					A_Explode(180,220, XF_HURTSOURCE);
			}
			Stop;
	}
	void SpawnExplosionParticleHeavySpark()
	{
		FSpawnParticleParams PUFSPRK;
		PUFSPRK.Texture = TexMan.CheckForTexture("SPRKS0");
		PUFSPRK.Color1 = "FFFFFF";
		PUFSPRK.Style = STYLE_Add;
		PUFSPRK.Flags = SPF_ROLL | SPF_FULLBRIGHT;
		PUFSPRK.Vel =(random(-5,5),random(-5,5),random(-2,9));
		PUFSPRK.accel =(0,0,frandom(-1.75,-0.75));
		PUFSPRK.Startroll = random(0, 359);
		PUFSPRK.RollVel = 0;
		PUFSPRK.StartAlpha = 1.0;
		PUFSPRK.FadeStep = 0.075;
		PUFSPRK.Size = 6.4;
		PUFSPRK.SizeStep = -0.5;
		PUFSPRK.Lifetime = random(12,18); 
		PUFSPRK.Pos = pos;
		Level.SpawnParticle(PUFSPRK);
	}

	void SpawnShrapnerParticleSpark()
	{
		FSpawnParticleParams PUFSPRK;
		PUFSPRK.Texture = TexMan.CheckForTexture("SPKOA0");
		PUFSPRK.Color1 = "FFFFFF";
		PUFSPRK.Style = STYLE_Add;
		PUFSPRK.Flags = SPF_ROLL | SPF_FULLBRIGHT;
		PUFSPRK.Vel =(random(-20, 20),random(-20, 20),random(-20, 20));
		PUFSPRK.accel =(0,0,0);
		PUFSPRK.Startroll = random(0, 359);
		PUFSPRK.RollVel = 0;
		PUFSPRK.StartAlpha = 1.0;
		PUFSPRK.FadeStep = 0.05;
		PUFSPRK.Size = 15.36;
		PUFSPRK.SizeStep = -0.05;
		PUFSPRK.Lifetime = 5; 
		PUFSPRK.Pos = pos;
		Level.SpawnParticle(PUFSPRK);
	}
}
class MarineGrenadeAnother: MarineThrownGrenade{
	Default{
	+BOUNCEONFLOORS
	+BOUNCEONWALLS
	+BOUNCEONCEILINGS
	-BOUNCEONACTORS
	-ALLOWBOUNCEONACTORS
	-EXTREMEDEATH
	+NOEXTREMEDEATH
	BounceFactor 0.600;
	BounceSound "grenade/bounce";
	}
}