Class PB_CapturedMarine: SwitchableDecoration{
	mixin PB_RandomMarineNameHandler;
	mixin PB_MarineSpawnHandler;
	Class<PBMarine> MarineType;
	String MarineTypeString;
	void SetMarineType(string marineTypeToSet){
		if(marineTypeToSet && debugLog){A_Log(string.format("SETTING MARINE TYPE"));}
		class<PBMarine> toSet = marineTypeToSet;
		if(toSet){
			if(debugLog){A_Log(string.format("Setting successful"));}
			self.MarineTypeString = marineTypeToSet;
			self.MarineType = toSet;
			//if(self.GetTag() == self.GetClassName()){
			let toSet2 = PBMarine(GetDefaultByType(toSet));
			if(toSet2 && toSet2.MarineWeapon){
				let MarineWeaponToTag = GetDefaultByType(toSet2.MarineWeapon);
				if(MarineWeaponToTag){
					string weaponTag = MarineWeaponToTag.GetTag();
					SetTag(string.format("%s [%s]",PickRandomName(RANK_MILITARY),weaponTag));
				}
			}else{SetTag(PickRandomName(RANK_MILITARY));}
			//}
		}
	}
	void SelectMarineType(){
		Stats = PB_GlobalStats.Get();
		int Count = PB_GlobalStats.Get().Counters[PB_GlobalStats.Counter_LevelsCompleted];
		if(self.cursector.IsSecret()){
			Count += (levelsToPlay/4);
			if(debugLog){A_Log("Is Secret");}
		}
		Count = Clamp(Count,1,levelsToPlay);
		string msg = String.Format("Tier Count: %d", Count);
		if(debugLog){A_Log(msg);}
		if(SpawnBalance==663){SetMarineType(Marine_Chaotic_Random_Name_List[random(0,Marine_Chaotic_Random_Name_List.size()-1)]);}
		else if(SpawnBalance==666 || SpawnBalance<=663 && SpawnBalance>=672){
			if(Count < (levelsToPlay / 4)) {SetMarineType(Marine_T1_Name_List[random(0,Marine_T1_Name_List.size()-1)]);}
			else if(Count == (levelsToPlay / 4)) {
				if(random(0,3) > 0){SetMarineType(Marine_T1_Name_List[random(0,Marine_T1_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
			}
			else if(Count == ((levelsToPlay / 4) + 1)) {
				if(random(0,1) > 0){SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T1_Name_List[random(0,Marine_T1_Name_List.size()-1)]);}
			}
			else if(Count == ((levelsToPlay / 4) + 2)) {
				if(random(0,3) > 0){SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T1_Name_List[random(0,Marine_T1_Name_List.size()-1)]);}
			}
			else if(Count < ((levelsToPlay / 4) * 2)) {SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
			
			else if(Count == ((levelsToPlay / 4) * 2)) {
				if(random(0,3) > 0){SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
			}
			else if(Count == (((levelsToPlay / 4) * 2) + 1)) {
				if(random(0,1) > 0){SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
			}
			else if(Count == (((levelsToPlay / 4) * 2) + 2)) {
				if(random(0,3) > 0){SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
			}
			else if(Count < ((levelsToPlay / 4) * 3)) {SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
			
			else if(Count == ((levelsToPlay / 4) * 3)) {
				if(random(0,3) > 0){SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T4_Name_List[random(0,Marine_T4_Name_List.size()-1)]);}
			}
			else if(Count == (((levelsToPlay / 4) * 3) + 1)) {
				if(random(0,1) > 0){SetMarineType(Marine_T4_Name_List[random(0,Marine_T4_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
			}
			else if(Count == (((levelsToPlay / 4) * 3) + 2)) {
				if(random(0,3) > 0){SetMarineType(Marine_T4_Name_List[random(0,Marine_T4_Name_List.size()-1)]);}
				else{SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
			}
			else if(Count > (((levelsToPlay / 4) * 3) + 2)) {SetMarineType(Marine_T4_Name_List[random(0,Marine_T4_Name_List.size()-1)]);}
		}
		else if(SpawnBalance==667){
			SetMarineType(Marine_T1_Name_List[random(0,Marine_T1_Name_List.size()-1)]);
		}
		else if(SpawnBalance==668){
			SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);
		}
		else if(SpawnBalance==669){
			SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);
		}
		else if(SpawnBalance==670||SpawnBalance==672){
			SetMarineType(Marine_T4_Name_List[random(0,Marine_T4_Name_List.size()-1)]);
		}
		else if(SpawnBalance==671){
			if(Count <= (levelsToPlay / 4)) {SetMarineType(Marine_T1_Name_List[random(0,Marine_T1_Name_List.size()-1)]);}
			else if(Count <= (levelsToPlay / 4 * 2)) {SetMarineType(Marine_T2_Name_List[random(0,Marine_T2_Name_List.size()-1)]);}
			else if(Count <= (levelsToPlay / 4 * 3)) {SetMarineType(Marine_T3_Name_List[random(0,Marine_T3_Name_List.size()-1)]);}
			else if(Count > (levelsToPlay / 4 * 3)) {SetMarineType(Marine_T4_Name_List[random(0,Marine_T4_Name_List.size()-1)]);}
		}
		if( NazisOnMap() ){SetMarineType(Marine_Wolfenstein_Name_List[random(0,Marine_Wolfenstein_Name_List.size()-1)]);}
	}
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, name damagetype){
		if(inflictor is "KnifeSwing" && source is "PlayerPawn" || inflictor is "PlayerPawn") return 0;
		else return super.TakeSpecialDamage(inflictor, source, damage, damagetype);
	}
	PB_GlobalStats Stats;
	override void PostBeginPlay(){
		if(!MarineTypeString){
			InitializeMarineLists();
			SelectMarineType();
		}
		if(MarineType){
			let def = GetDefaultByType(MarineType);
			if (!def){A_Log("Destroyed");Destroy();return;}
			self.scalex = def.scalex;
			self.scaley = def.scaley;
			self.translation = def.translation;
		}
		A_GiveInventory("TargetIsAMarine");
		Super.PostBeginPlay();
	}
	void A_SpawnMarine(){
		if(MarineType){
			actor MarineActor; bool b;
			class<PBMarine> toSet = self.MarineTypeString;
			if (MarineType is "PBMarine"){
				[b,MarineActor] = A_SpawnItemEx("Marine_Spawn",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | 288,0,tid);
				let Actor_Spawn = Marine_Spawn(MarineActor);
				if(MarineActor && self.GetTag() != self.GetClassName()){MarineActor.SetTag(self.GetTag());}
				class<PBMarine> SpawnedActorMarine = self.MarineTypeString;
				if(Actor_Spawn && SpawnedActorMarine){
					Actor_Spawn.MarineType = SpawnedActorMarine;
					Actor_Spawn.master = players[0].mo;
					Actor_Spawn.target = players[0].mo;
				}
			}
		}
		else{A_SpawnItemEx("PBMarineSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
	}
	Default{
	+LOOKALLAROUND;
	Monster; 
	-SOLID;
	-NOTIMEFREEZE;
	-COUNTKILL;
	+FORCEXYBILLBOARD;
	//Radius 24;
	ProjectilePassHeight 48;
	Health 300;
	Scale 1.0;
	Decal "BloodSuper";
	Species "Marines";
	Painchance 255;
	DamageType "Taunt";
	damagefactor "Trample", 0.0;
	damagefactor "Cut", 10.0;
	damagefactor "Taunt", 0.0;
	damagefactor "headcut", 0.0;
	damagefactor "KillMe", 0.0;
	damagefactor "Fatality", 99.0;
	damagefactor "Melee", 99.0;
	damagefactor "Kick", 99.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "TeleportRemover", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	DeathSound "*death";
	PainSound "*pain50";
	BloodType "Brutal_Blood";
	Activation THINGSPEC_Activate;
	//DropItem "PoleWithNothing", 255;
	Mass 999999;
	Speed 0;
	+SHOOTABLE
	+FLOORCLIP
	+SOLID
	-FRIENDLY
	-COUNTKILL
	+FLOORCLIP
	+THRUSPECIES
	+USESPECIAL
	}
	Override void Die(Actor source, Actor inflictor, int dmgflags, Name MeansOfDeath){
		bUSESPECIAL = false;
		Super.Die(source, inflictor, dmgflags, MeansOfDeath);
	}
	States{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
	HelpMe:
		TNT1 A 0 A_Stop();
		//A_JumpIfInTargetLOS()
		//
		//TNT1 A 0 A_CheckSight("Spawn2");
		//TNT1 A 0 A_ChangeFlag("FRIENDLY", 0);
		/*TNT1 A 0 {
			LookExParams params;
			params.fov = 180;
			params.flags = LOF_NOSOUNDCHECK|LOF_NOJUMP;
			params.minDist = 0;
			params.maxDist = 1024;
			params.seeState = ResolveState("See");
			if(LookForPlayers(false, params)){
				SetState(ResolveState("See"));
			}
		}*/
			/*
			if(LookForPlayers(false, params);){
				A_LookEx(LOF_NOSOUNDCHECK|LOF_NOJUMP,0,0,0,360,1);
				return ResolveState("See");
			}else{
				return ResolveState("Spawn2");
			}
			return ResolveState("");
			*/
		TNT1 A 0 A_JumpIf(bFRIENDLY,2);
		TNT1 A 0 A_LookEx(LOF_NOSOUNDCHECK|LOF_NOJUMP,0,0,0,360,1);
		Goto Spawn2;
	See:
		TNT1 A 0 A_ChangeFlag("FRIENDLY", 1);
		CAPT ABCB 15 A_Stop();
		TNT1 A 0 A_JumpIfInTargetLOS(1,180,JLOSF_DEADNOJUMP|JLOSF_CLOSENOJUMP,200,10);
		Loop;
		TNT1 A 0 {A_ChangeFlag("THRUSPECIES",1);A_CustomMissile("OrderTitle3", 50, 0, 0, 2, 90);
			if(target){
				if(!master || (master && target != master)){
					target.A_Print("Get me out of here!!!"); master = target;
					A_AlertMonsters(500,AMF_TARGETEMITTER);
				}
			}
		}
		Loop;
	Spawn2:
		CAPT A 5 ;//A_ChangeFlag("FRIENDLY", 1);
		Goto HelpMe;
	SetFree:
	Pain.Cut:
	Death.Cut:
	Pain.Melee:
	Death.Melee:
	Pain.SuperPunch:
	Death.SuperPunch:
	Pain.Fatality:
	Death.Fatality:
	Pain.Kick:
	Death.Kick:
	Death.Telefrag:
	Active:
		CAPT F 1 ;
		CAPT F 12 {
			if(!pb_quietmarines){A_Playsound("marine/freed");}
			A_ChangeFLag("NOPAIN", 1);
		}
		TNT1 A 0 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 A 0 A_JumpIfInTargetInventory("AllySummoner",1,2);
		TNT1 A 0 {A_GiveToTarget("AllySummoner",1);A_GiveToTarget("CalledInAllies",1);}
		CAPT N 1 A_SpawnMarine;
		Stop;
	Pain:
	Pain.Blast:
	Pain.ExplosiveImpact:
	Pain.Explosive:
	Pain.Bullet:
	Pain.SSG:
	Pain.CutLess:
	Pain.ImpFatalityMarine:
	Pain.Rip:
		CAPT P 1;
		CAPT P 5 {A_Stop();A_Pain();}
		TNT1 A 0 A_Stop();
		Goto HelpMe;
	Death:
	Death.Bullet:
		PLAY H 10 {A_PlayerScream();A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));}
		PLAY I 10 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		PLAY JKLM 10 ;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		PLAY N -1;
		Stop;
	Death.Eat:
		XPL1 A 10 {A_GiveToTarget("EatMe",1);
		A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		A_XScream();
		}
		XPL1 B 20 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		XPL1 CDE 10 ;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL1 E -1;
		Stop;
	Death.Cut:
	Death.Saw:
		TNT1 A 0 {A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		A_XScream();}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 ;
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL2 E -1;
		Stop;
	Death.Slime:
		TNT1 A 0 A_PlaySound("BIGSCREA");
		PMET AABBCCDDEEFFGGHHIIIII 10 A_CustomMissile("PlasmaSmoke", 25, 0, random (0, 180), 2, random (0, 180));
		PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 A_CustomMissile("PlasmaSmoke", 25, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 A -1;
		Stop;
	Death.CutLess:
		TNT1 A 0 A_Jump (128, "Death");
		TNT1 A 0 {A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream();
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL2 E -1;
		Stop;
	Death.Rip:
		TNT1 AAAAAAAAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 A 10 A_XScream();
		TNT1 AAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 B 20 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 A 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 C 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 D 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 E 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL3 F -1;
		Stop;
	Death.Massacre:
	Death.Explosives:
	XDeath:
		TNT1 A 0 {ThrustThingZ(0,60,0,1);
		A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		A_SpawnItemEx("BasicMarineGib2", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		A_SpawnItemEx("BasicMarineGib3", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		A_SpawnItemEx("BasicMarineGib4", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		A_CustomMissile("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		A_XScream();
		{A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		A_CustomMissile("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 90));
		A_SpawnItem ("BigBloodSpot");}
		TNT1 AAAAA 0 A_CustomMissile("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAA 0 A_CustomMissile("SuperWallRedBlood", 40, 0, random (0, 360), 2, random (-5, 5));
		TNT1 AAAAAA 0 bright A_CustomMissile("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		Stop;
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile("Brutal_FlyingBloodTrail8", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 bright {A_CustomMissile("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));A_CustomMissile("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));}
		TNT1 AA 0 bright {A_CustomMissile("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));A_CustomMissile("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));}
		TNT1 A 1 {A_SpawnItem("GrowingBloodPool");A_SpawnItem("CrushedRemains");}
		TNT1 A 1 A_XScream();
		TNT1 A 1 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		Stop;
	Death.Blast:
	Death.SuperPunch:
	Death.SSG:
		PLAY O 2 A_FaceTarget;
		TNT1 AAAA 0 {A_CustomMissile("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		A_CustomMissile("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		}
		TNT1 A 0 {A_CustomMissile("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));A_XScream();{A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}}
		PLAY OPQRSTU 8;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		PLAY U -1;
		Stop;
	Death.Destruction:
		TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 A 20 A_XScream();
		TNT1 A 0 {A_CustomMissile("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));}
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 B 20 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 C 20;
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 D 20;
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 E 20;
		TNT1 AAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 F 20;
		TNT1 AAAA 0 A_CustomMissile("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL4 F -1;
		Stop;
	Death.plasma:
		TNT1 A 0 {A_XScream();{A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		A_CustomMissile("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));}
		TNT1 AAA 0 A_CustomMissile("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAAAA 0 A_CustomMissile("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 1;
		TNT1 A -1;
		Stop;
		Death.GreenFire:
		TNT1 A 0 {A_XScream();{A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		A_CustomMissile("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));}
		TNT1 AAAA 0 A_CustomMissile("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
		Stop;
	Death.burn:
		PBUR A 1;
		PBUR A 1 A_Scream();
		PBUR A 1 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		PBUR AAAABBBBCCCC 2 A_CustomMissile("SmallFlameTrails", 32, 0, random (0, 180), 2, random (0, 180));
		PBUR DDDDEEEE 2 A_CustomMissile("SmallFlameTrails", 16, 0, random (0, 180), 2, random (0, 180));
		PBUR EEEEE 4 A_CustomMissile("SmallFlameTrails", 8, 0, random (0, 180), 2, random (0, 180));
		PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		PBUR E -1;
		Stop;
	Death.Fire:
	Death.Flames:
		BURN W 6 {A_PlaySound("BIGSCREA");A_Scream();}
		BURN X 6 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		BUR2 ABCD 6 BRIGHT A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN FGHIJKL 6 BRIGHT A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN MNOPQRSTUV 6 BRIGHT A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 6 A_CustomMissile("PlasmaSmoke", 8, 0, random (0, 180), 2, random (0, 180));
		BURN V -1;
	Stop;
	Death.ExplosiveImpact:
		NULL AAAA 0 A_CustomMissile("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		PPOD A 0 {ThrustThingZ(0,30,0,1);A_CustomMissile("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("Brains4", 50, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		A_CustomMissile("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);}
		NULL AAAA 0 {A_CustomMissile("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));A_CustomMissile("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));}
		NULL AA 0 A_CustomMissile("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		NULL AAAAAAAAAAA 0 A_CustomMissile("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		NULL AAAA 0 A_CustomMissile("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		XPL6 A 5 A_XScream();
		XPL6 B 5 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		XPL6 CDE 5;
		XPL6 F -1;
		Stop;
	Crush:
		CRS1 A 5 A_PlaySound("misc/xdeath4");
		CRS1 A -1;
		Stop;
	Death.HKFT:
	Death.BHFT:
	Death.RVFT:
		TNT1 A 1 A_PlayerScream();
		TNT1 A 1 {A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}
		TNT1 A 0 A_GiveToTarget("Curbstomp_Marine",1);
		TNT1 A -1;
		Stop;
	Death.FatalityMarine:
		TNT1 A 1 A_PlayerScream();
		TNT1 A 1 {A_GiveToTarget("GoFatality", 1);{A_NoBlocking();A_SpawnItemEx("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH|SXF_TRANSFERSCALE,0);}}
		TNT1 A 0 A_GiveToTarget("Fatality_Marine",1);
		TNT1 A -1;
		Stop;
	}
}
Class PoleWithNothing : Actor{
	Default{
		Mass 99999999;
		+NOBLOCKMAP
	}
	States{
	Spawn:
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_SpawnItem("PoleWithNothing2", 0, -40);
			Stop;
	}
}

Class PoleWithNothing2 : PoleWithNothing{
	States{
	Spawn:
			CAPT N 1 A_Stop;
			CAPT N -1;
			Stop;
	}
}