Class PBMarineSpawnerNoKeep : PBMarineSpawner{
	States{
	Tier4:
		TNT1 A 0 A_Jump(4, "SpawnMarineDoom");
		TNT1 A 0 A_Jump(256, "SpawnTier4Randomizer");
	Tier3:
		TNT1 A 0 A_Jump(256, "SpawnTier3Randomizer");
	Tier2:
		TNT1 A 0 A_Jump(256, "SpawnTier2Randomizer");
	Tier1:
		TNT1 A 0 A_Jump(256, "SpawnTier1Randomizer");
	SpawnTier1Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerNoKeepT1");
		Stop;
	SpawnTier2Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerNoKeepT2");
		Stop;
	SpawnTier3Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerNoKeepT3");
		Stop;
	SpawnTier4Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerNoKeepT4");
		Stop;
	}
}

class PB_MarineSpawnerNoKeepT1 : PB_MarineSpawner{
	Default{
		DropItem 'Marine_Rifle', 255, 1;
		DropItem 'Marine_SMG', 255, 1;
		DropItem 'Marine_Minigun', 255, 1;
		DropItem 'Marine_Shotgun', 255, 1;
	}
}
class PB_MarineSpawnerNoKeepT2 : PB_MarineSpawner{
	Default{
		DropItem 'PB_MarineSpawnerNoKeepT1',255,1;
		DropItem 'Marine_Revolver', 255, 1;
		DropItem 'Marine_Carbine', 255, 1;
		DropItem 'Marine_AutoShotgun', 255, 1;
		DropItem 'Marine_SuperShotgun', 255, 1;
		DropItem 'Marine_PlasmaGun', 255, 1;
	}
}
class PB_MarineSpawnerNoKeepNaziWeapons : PB_MarineSpawner{
	Default{
		DropItem 'Marine_MG42', 255, 1;
		DropItem 'Marine_MP40', 255, 3;
	}
}
class PB_MarineSpawnerNoKeepT3 : PB_MarineSpawner{
	Default{
		DropItem 'PB_MarineSpawnerNoKeepT1',255,1;
		DropItem 'PB_MarineSpawnerNoKeepT2',255,1;
		DropItem 'Marine_Deagle', 255, 1;
		DropItem 'Marine_SuperShotgun', 255, 1;
		DropItem 'Marine_Nailgun', 255, 1;
		DropItem 'Marine_M2Plasma', 255, 1;
		DropItem 'Marine_Flamethrower', 255, 1;
		DropItem 'Marine_Rocket', 255, 1;
		DropItem 'Marine_GL', 255, 1;
	}
}
class PB_MarineSpawnerNoKeepT4 : PB_MarineSpawner{
	Default{
		//DropItem 'PB_EliteMarineSpawner',255,1;
		DropItem 'PB_MarineSpawnerNoKeepT1',255,2;
		DropItem 'PB_MarineSpawnerNoKeepT2',255,2;
		DropItem 'PB_MarineSpawnerNoKeepT3',255,2;
		DropItem 'Marine_LMG', 255, 2;
		DropItem 'Marine_Demontech', 255, 2;
		DropItem 'Marine_PulseCannon', 255, 2;
		DropItem 'Marine_Railgun', 255, 2;
		DropItem 'Marine_BFG', 255, 1;
	}
}