Class PBMarineSpawner : PB_SpawnerBase{
	mixin PB_MarineSpawnHandler;
	default{
	+LOOKALLAROUND;
	scale 0.45;
	-SHOOTABLE;
	-COUNTKILL; 
	-SOLID;
	+NOTIMEFREEZE;
	Species "Marines";
	}
	Action void A_SpawnMarineActorEx(class<Actor> SpawnedActor){
		bool a; Actor newActor;
		if (SpawnedActor is "PBMarine"){
			[a,newActor] = A_SpawnItemEx("Marine_Spawn",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | 288,0,tid);
			newActor.master = players[0].mo;newActor.target = players[0].mo;
			let Actor_Spawn = Marine_Spawn(newActor);
			class<PBMarine> SpawnedActorMarine = SpawnedActor.GetClassName();
			if(Actor_Spawn && SpawnedActorMarine){
				Actor_Spawn.MarineType = SpawnedActorMarine;
			}
		}
		else{
			[a,newActor] = A_SpawnItemEx(SpawnedActor,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | 288,0,tid);
			if(newActor is "Marine_Spawn"){newActor.master = players[0].mo;newActor.target = players[0].mo;}
			if(newActor is "PB_MarineSpawner"){newActor.master = players[0].mo;newActor.target = players[0].mo;}
		}
	}
	States{
		/*
		Spawn:
			TNT1 A 0;
		Spawn2:	
			TNT1 A 0;
		InitiateCheck:
			TNT1 A 1;
			TNT1 A 0{
				Stats = PB_GlobalStats.Get();
				//int Count = Clamp(Stats.Counters[PB_GlobalStats.Counter_LevelsCompleted] + (self.cursector.IsSecret()?(levelsToPlay/4):0),1,levelsToPlay);//int Count = Stats.Counters[PB_GlobalStats.Counter_LevelsCompleted];
				int Count = Stats.Counters[PB_GlobalStats.Counter_LevelsCompleted];
				if(SpawnBalance==663){{SetStateLabel("CHAOTICRANDOM");}}
				else if(SpawnBalance==666||SpawnBalance<=663&&SpawnBalance>=672){
					if(Count < (levelsToPlay / 4)) {SetStateLabel("Tier1");}
					
					else if(Count == (levelsToPlay / 4)) {SetStateLabel("T2Random64");}
					else if(Count == ((levelsToPlay / 4) + 1)) {SetStateLabel("T2Random128");}
					else if(Count == ((levelsToPlay / 4) + 2)) {SetStateLabel("T2Random192");}
					
					else if(Count < ((levelsToPlay / 4) * 2)) {SetStateLabel("Tier2");}
					
					else if(Count == ((levelsToPlay / 4) * 2)) {SetStateLabel("T3Random64");}
					else if(Count == (((levelsToPlay / 4) * 2) + 1)) {SetStateLabel("T3Random128");}
					else if(Count == (((levelsToPlay / 4) * 2) + 2)) {SetStateLabel("T3Random192");}
					
					else if(Count < ((levelsToPlay / 4) * 3)) {SetStateLabel("Tier3");}
					
					else if(Count == ((levelsToPlay / 4) * 3)) {SetStateLabel("T4Random64");}
					else if(Count == (((levelsToPlay / 4) * 3) + 1)) {SetStateLabel("T4Random128");}
					else if(Count == (((levelsToPlay / 4) * 3) + 2)) {SetStateLabel("T4Random192");}
					
					else if(Count > (((levelsToPlay / 4) * 3) + 2)) {SetStateLabel("Tier4");}
				}
				else if(SpawnBalance==667){
				{SetStateLabel("Tier1");}
				}
				else if(SpawnBalance==668){
				{SetStateLabel("Tier2");}
				}
				else if(SpawnBalance==669){
				{SetStateLabel("Tier3");}
				}
				else if(SpawnBalance==670||SpawnBalance==672){
				{SetStateLabel("Tier4");}
				}
				else if(SpawnBalance==671){
					if(Count <= (levelsToPlay / 4)) {SetStateLabel("Tier1");}
					else if(Count <= (levelsToPlay / 4 * 2)) {SetStateLabel("Tier2");}
					else if(Count <= (levelsToPlay / 4 * 3)) {SetStateLabel("Tier3");}
					else if(Count > (levelsToPlay / 4 * 3)) {SetStateLabel("Tier4");}
				}
			}
			Loop;
		T2Random64:
			TNT1 A 0 A_Jump(64,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T2Random128:
			TNT1 A 0 A_Jump(128,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T2Random192:
			TNT1 A 0 A_Jump(192,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T3Random64:
			TNT1 A 0 A_Jump(64,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier1","Tier2");
		T3Random128:
			TNT1 A 0 A_Jump(128,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier1","Tier2","Tier2");
			TNT1 A 0 A_Jump(256,"Tier2");
		T3Random192:
			TNT1 A 0 A_Jump(192,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier1","Tier2","Tier2");
			TNT1 A 0 A_Jump(256,"Tier2");
		T4Random64:
			TNT1 A 0 A_Jump(64,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier1","Tier2","Tier2","Tier3","Tier3","Tier3");
			TNT1 A 0 A_Jump(256,"Tier3");
		T4Random128:
			TNT1 A 0 A_Jump(128,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier1","Tier2","Tier2","Tier3","Tier3","Tier3");
			TNT1 A 0 A_Jump(256,"Tier3");
		T4Random192:
			TNT1 A 0 A_Jump(192,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier1","Tier2","Tier3","Tier3");
			TNT1 A 0 A_Jump(256,"Tier3");
		CHAOTICRANDOM:
			TNT1 A 0 A_Jump(256, "Tier4","Tier3", "Tier2", "Tier1");
			Stop;
			*/
	Tier4:
		TNT1 A 0 A_Jump(4, "SpawnMarineDoom");
		TNT1 A 0 A_Jump(256, "SpawnTier4Randomizer");
		
		/*
		TNT1 A 0 A_Jump(96, "SpawnTier4Randomizer");
		TNT1 A 0 A_JumpIf(pb_bfgmarines,3);
		TNT1 A 0 A_Jump(32, "SpawnMarineRailgun");
		TNT1 A 0 A_Jump(256,2);
		TNT1 A 0 A_Jump(32, "SpawnMarineRailgun", "SpawnMarineRailgun","SpawnMarineBFG");
		TNT1 A 0 A_Jump(32, "SpawnMarineRailgun");
		TNT1 A 0 A_JumpIf(pb_explosivemarines,3);
		TNT1 A 0 A_Jump(256,2);
		TNT1 A 0 A_Jump(256,"SpawnMarineRocket","SpawnMarineGL","SpawnMarineNailgun","SpawnMarinePulseCannon");
		TNT1 A 0 A_Jump(256,"SpawnMarineNailgun","SpawnMarinePulseCannon");
		*/
	Tier3:
		TNT1 A 0 A_Jump(256, "SpawnTier3Randomizer");
		/*
		TNT1 A 0 A_Jump(96, "SpawnTier3Randomizer");
		TNT1 A 0 A_Jump(32, "SpawnMarineM2Plasma");
		TNT1 A 0 A_Jump(256,"SpawnMarineShotgun","SpawnMarineSuperShotgun","SpawnMarineMinigun","SpawnMarinePlasma","SpawnMarineFlamethrower");
		*/
	Tier2:
		TNT1 A 0 A_Jump(256, "SpawnTier2Randomizer");
		/*
		TNT1 A 0 A_Jump(96, "SpawnTier2Randomizer");
		TNT1 A 0 A_Jump(256,"SpawnMarineSMG","SpawnMarineMinigun","SpawnMarineSuperShotgun","SpawnMarineCarbine","SpawnMarineRevolver");
		*/
	Tier1:
		TNT1 A 0 A_Jump(256, "SpawnTier1Randomizer");
		/*
		TNT1 A 0 A_Jump(96, "SpawnTier1Randomizer");
		TNT1 A 0 A_Jump(256,"SpawnMarineRifle","SpawnMarineShotgun");
		*/
	SpawnTier1Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerT1");
		Stop;
	SpawnTier2Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerT2");
		Stop;
	SpawnTier3Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerT3");
		Stop;
	SpawnTier4Randomizer:
		TNT1 A 0 A_SpawnMarineActorEx("PB_MarineSpawnerT4");
		Stop;
	SpawnMarineRevolver:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnRevolver");
		Stop;
	SpawnMarineRifle:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnRifle");
		Stop;
	SpawnMarineCarbine:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnCarbine");
		Stop;
	SpawnMarineSMG:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnSMG");
		Stop;
	SpawnMarineMP40:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnMP40");
		Stop;
	SpawnMarineMG42:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnMG42");
		Stop;
	SpawnMarineShotgun:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnShotgun");
		Stop;
	SpawnMarineSuperShotgun:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnSuperShotgun");
		Stop;
	SpawnMarineAutoShotgun:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnAutoShotgun");
		Stop;
	SpawnMarineMinigun:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnMinigun");
		Stop;
	SpawnMarineNailgun:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnNailgun");
		Stop;
	SpawnMarineRocket:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnRocket");
		Stop;
	SpawnMarineGL:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnGL");
		Stop;
	SpawnMarinePlasma:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnPlasmaGun");
		Stop;
	SpawnMarineM2Plasma:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnM2Plasma");
		Stop;
	SpawnMarinePulseCannon:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnPulseCannon");
		Stop;
	SpawnMarineFlamethrower:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnFlamethrower");
		Stop;
	SpawnMarineRailgun:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnRailgun");
		Stop;
	SpawnMarineBFG:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnBFG");
		Stop;
	SpawnMarineDoom:
		TNT1 A 0 A_SpawnMarineActorEx("Marine_SpawnDoom");
		Stop;
	SpawnEliteMarine:
		TNT1 A 0 A_SpawnMarineActorEx("PB_EliteMarineSpawner");
		Stop;
	}
}
class PB_MarineSpawnerT1 : PB_MarineSpawner{
	Default{
		DropItem 'Marine_SpawnRifle', 255, 1;
		DropItem 'Marine_SpawnSMG', 255, 1;
		DropItem 'Marine_SpawnMinigun', 255, 1;
		DropItem 'Marine_SpawnShotgun', 255, 1;
	}
}
class PB_MarineSpawnerT2 : PB_MarineSpawner{
	Default{
		//DropItem 'PB_MarineSpawnerT1',255,1;
		DropItem 'Marine_SpawnRevolver', 255, 1;
		DropItem 'Marine_SpawnCarbine', 255, 1;
		DropItem 'Marine_SpawnAutoShotgun', 255, 1;
		DropItem 'Marine_SpawnSuperShotgun', 255, 1;
		DropItem 'Marine_SpawnPlasmaGun', 255, 1;
	}
}
class PB_MarineSpawnerNaziWeapons : PB_MarineSpawner{
	Default{
		DropItem 'Marine_SpawnMG42', 255, 1;
		DropItem 'Marine_SpawnMP40', 255, 3;
	}
}
class PB_MarineSpawnerT3 : PB_MarineSpawner{
	Default{
		DropItem 'Marine_SpawnDeagle', 255, 1;
		DropItem 'Marine_SpawnSuperShotgun', 255, 1;
		DropItem 'Marine_SpawnNailgun', 255, 1;
		DropItem 'Marine_SpawnM2Plasma', 255, 1;
		DropItem 'Marine_SpawnFlamethrower', 255, 1;
		DropItem 'Marine_SpawnRocket', 255, 1;
		DropItem 'Marine_SpawnGL', 255, 1;
	}
}
class PB_MarineSpawnerT4 : PB_MarineSpawner{
	Default{
		//DropItem 'PB_EliteMarineSpawner',255,1;
		DropItem 'Marine_SpawnLMG', 255, 2;
		DropItem 'Marine_SpawnDemontech', 255, 2;
		DropItem 'Marine_SpawnPulseCannon', 255, 2;
		DropItem 'Marine_SpawnRailgun', 255, 2;
		DropItem 'Marine_SpawnBFG', 255, 1;
	}
	/*
	static const String PB_MarineT3ListNonExplosive[] = {"Marine_SpawnDeagle","Marine_SpawnSuperShotgun","Marine_SpawnNailgun","Marine_SpawnM2Plasma","Marine_SpawnFlamethrower"};
	static const String PB_MarineT4ListNonBFG[] = {"Marine_SpawnLMG","Marine_SpawnDemontech","Marine_SpawnPulseCannon","Marine_SpawnRailgun"};
	override void HandleSpawnExeptions(in out name toSpawn){
		if(pb_explosivemarines && (toSpawn == "Marine_SpawnRocket" || toSpawn == "Marine_SpawnGL"))
			toSpawn = PB_MarineT3ListNonExplosive[random(0,PB_MarineT3ListNonExplosive.Size()-1)];
		if(pb_bfgmarines && (toSpawn == "Marine_SpawnRocket" || toSpawn == "Marine_SpawnGL")){
			toSpawn = PB_MarineT3ListNonExplosive[random(0,PB_MarineT3ListNonExplosive.Size()-1)];
		}
	}
	*/
}
class PB_EliteMarineSpawner : PB_MarineSpawner{
	Default{
		DropItem "Marine_SpawnEliteASG";
		DropItem "Marine_SpawnEliteCarbine";
		DropItem "Marine_SpawnEliteRifle";
		DropItem "Marine_SpawnEliteMinigun";
		DropItem "Marine_SpawnEliteShotgun";
		DropItem "Marine_SpawnMarshall";
	}
}